lang = {
    -- notifications
    ['no_perms'] = "You don't have enough permissions.",
    
    --menu
    ['time_in_mints'] = 'Time in mints',
    ['time_in_mints_description'] = 'Car wipe after Mints? effect on next server restart',
    ['wipe_options'] = 'Wipe option',
    ['broken_only'] = 'Broken Only',
    ['broken_repair'] = "Broken + Repair",
    ['class_wise_whitelist'] = 'Class wise Whitelist',
    ['class_wise_whitelist_description'] = 'selected classes veicles will not be wiped',
    ['model_wise_whitelist'] = 'Model wise Whitelist',
    ['model_wise_whitelist_description'] = "write model without inverted comma's",
    ['plate_wise_whitelist'] = 'Plate wise Whitelist',
    ['plate_wise_whitelist_description'] = "write plate without inverted comma's",
    ['zone_command_settings'] = 'Zone Command Settings',
    ['command_name'] = 'Command Name',
    ['whitelist_groups'] = 'Whitelist Groups',
    ['admin_that_can_usea_command'] = 'these admin groups can use that commmand',
    ['general_wipe_settings'] = 'General Wipe Settings',
    ['modify_commands'] = 'Modify Commands',
    ['main_admin_carwipe_menu'] = 'Main Admin CarWipe Menu',
    ['command_settings'] = 'Commands Settings',
    ['admin_menu_command_settings'] = 'Admin Menu Command Settings',
    ['zones_command_settings'] = 'Zones Commands Settings',
    ['instant_wipe_command_settings'] = 'Instant Wipe Command Settings',
    ['create_new_wipe_zone'] = 'Create New Wipe Zone',
    ['create_new_zone'] = 'Create New Zone',
    ['zone_name'] = 'Zone Name',
    ['zone_name_description'] = 'Zone name for menus',
    ['radius_of_zone'] = 'Radius of Zone',
    ['radius_of_zone_description'] = 'Radius around you current location for zone',
    ['confirmation_message'] = 'Confirmation Message',
    ['confirmation_message_content'] = 'Are you sure you want to delete this zone?',
    ['zone_menu'] = 'Zone Menu',
    ['command_work_on_restart'] = 'command will change on next restart',
    ['job_can_use_this_commmand'] = 'these jobs can use that commmand',
    ['max_radius'] = 'Max Radius',
    ['max_radius_description'] = 'max zone radius can be',
    ['default_radius'] = 'Default Radius',
    ['default_radius_description'] = 'Default zone radius can be',
    ['zone_color'] = 'Zone Color',
    ['zone_color_description'] = 'get color id from fivem blips colors on google',
    ['zone_color_alpha'] = 'Zone Color Alpha',
    ['zone_color_alpha_description'] = 'Set Zone Alpha',
    ['wipe_command_settings'] = 'Wipe Command Settings'
}