--------------------------------------
----- Created by Adzeepulse#7832 -----
--------------------------------------

LangClient = {
  ["ENG"] = {
    notifications = {
        ['vote_submit'] = "You have registered your vote!",
        ['vote_error'] = "Please Choose A Candidate!",
        ['apply_candidate_error'] = "You need to fill in all questions!",
        ['apply_candidate_length_error_one'] = "Short Description can not be longer then %s words including spaces!",
        ['apply_candidate_length_error_two'] = "Why do you want to be a candidate can not be longer then %s words including spaces!",
        ['apply_candidate_length_error_three'] = "What would you bring to the city can not be longer then %s words including spaces!",
        ['denied_candidate_error'] = "You need to fill in the reason!",
        ['start_voting_error'] = "You can only start the candidate applications once the last election winner has claimed there job!",
        ['message_owner_error'] = "You need to fill in the reason!",
        ['change_city_tax_error_one'] = "You need to input an amount lower then 1.0, e.g 0.25!",
        ['change_city_tax_error_two'] = "You can not go higher then the capped amount of %s%s",
        ['open_voting_ui_error_one'] = "You have already submitted a vote.",
        ['open_voting_ui_error_two'] = "Voting booths are not ready for using, please come back when the voting has started!",
        ['removeCandidate_error'] = "You need to fill in the reason!",
        ['calcalateTimeClient'] = "%s days, %s hours, and %s minutes.",
        ['open_law_voting_error'] = "This system is currently being built by the government, please come back later.",
    },
    menus = {
        ['applyCandidate_ap_court_title'] = "Application",
        ['applyCandidate_ap_court_header'] = "Candidate App: [<span style='color:Red;'>NOT AUTHORISED</span>]",
        ['applyCandidate_ap_court_header_OX'] = "Candidate App: NOT AUTHORISED",
        ['applyCandidate_ap_court_txt'] = "You are not able to apply to become a candidate, this is because you have a criminal record on file. You can apply for this position if your record gets wiped.",
        
        ['applyCandidate_state_six_header'] = "Candidate Status: [<span style='color:Red;'>REMOVED</span>]",
        ['applyCandidate_state_six_header_OX'] = "Candidate Status: REMOVED",
        ['applyCandidate_state_six_txt'] = "You have been removed due to: %s, you will not be able to reapply until the next election.",

        ['applyCandidate_state_five_header_one'] = "Voting Status: [<span style='color:Green;'>WINNER</span>]",
        ['applyCandidate_state_five_header_one_OX'] = "Voting Status: WINNER",
        ['applyCandidate_state_five_header_two'] = "Start %s Job",
        ['applyCandidate_state_five_txt_one'] = "Congratulation, you are the winner and had the max amount of votes.",
        ['applyCandidate_state_five_txt_two'] = "Click here to be assigned the %s job.",
        
        ['applyCandidate_state_four_header'] = "Voting Status: [<span style='color:Green;'>STARTED</span>]",
        ['applyCandidate_state_four_header_OX'] = "Voting Status: STARTED",
        ['applyCandidate_state_four_txt'] = "Amount of votes: <span style='color:Green;'>%s</span>",
        ['applyCandidate_state_four_txt_OX'] = "Amount of votes: %s",

        ['applyCandidate_state_three_header'] = "Candidate Status: [<span style='color:Green;'>APPROVED</span>]",
        ['applyCandidate_state_three_header_OX'] = "Candidate Status: APPROVED",
        ['applyCandidate_state_three_txt'] = "Your application has been approved, your candidacy has now started. You will now be able to advertise yourself to the public for when the poll starts.",

        ['applyCandidate_state_two_header'] = "Candidate Status: [<span style='color:Red;'>DENIED</span>]",
        ['applyCandidate_state_two_header_OX'] = "Candidate Status: DENIED",
        ['applyCandidate_state_two_txt'] = "Thank you for your intrest but your application has been denied due to: %s, you will not be able to reapply until the next election.",

        ['applyCandidate_state_one_header'] = "Candidate Status: [<span style='color:Green;'>APPLIED</span>]",
        ['applyCandidate_state_one_header_OX'] = "Candidate Status: APPLIED",
        ['applyCandidate_state_one_txt'] = "Thank you for applying to be a candidate your application is pending checks from the government staff.",
        
        ['applyCandidate_state_zero_header_one'] = "Candidate Applications: [<span style='color:Green;'>OPEN</span>]",
        ['applyCandidate_state_zero_header_one_OX'] = "Candidate Applications: OPEN",
        ['applyCandidate_state_zero_header_two'] = "Candidate Applications: [<span style='color:Red;'>CLOSED</span>]",
        ['applyCandidate_state_zero_header_two_OX'] = "Candidate Applications: CLOSED",
        ['applyCandidate_state_zero_txt_one'] = "If you feel like your a suitable candidate, please click to apply.",
        ['applyCandidate_state_zero_txt_two'] = "Candidate applications are currently closed, please keep an eye out for announcments.",

        ['viewRequestedCandidates_header_one'] = "Candidate Applications",
        ['viewRequestedCandidates_header_two'] = "Candidate Name: %s",
        ['viewRequestedCandidates_txt_one'] = " ",
        ['viewRequestedCandidates_txt_two'] = "Click to see more information!",

        ['getCandidateInfo_title'] = "Candidate information",
        ['getCandidateInfo_header_one'] = "Candidate Name",
        ['getCandidateInfo_header_two'] = "Short Description?",
        ['getCandidateInfo_header_three'] = "Why did you apply?",
        ['getCandidateInfo_header_four'] = "What would you bring to the city?",
        ['getCandidateInfo_header_five'] = "Accept Application",
        ['getCandidateInfo_header_six'] = "Deny Application",
        ['getCandidateInfo_txt_one'] = "%s",
        ['getCandidateInfo_txt_two'] = "%s",
        ['getCandidateInfo_txt_three'] = "%s",
        ['getCandidateInfo_txt_four'] = "%s",
        ['getCandidateInfo_txt_five'] = "Click here to add the candidate to the candidacy list.",
        ['getCandidateInfo_txt_six'] = "Click here to remove %s application from this voting poll.",

        ['startVoting_title'] = "Voting Types",
        ['startVoting_header'] = "Poll: %s",
        ['startVoting_txt'] = "Click here to start the voting.",

        ['manageCandidate_title'] = "Candidate Description",
        ['manageCandidate_header_one'] = "Candidates Name:",
        ['manageCandidate_header_two'] = "Short Description?",
        ['manageCandidate_header_three'] = "Why do you want to be a candidate?",
        ['manageCandidate_header_four'] = "What would you bring to the city?",
        ['manageCandidate_header_five'] = "Current Votes:",
        ['manageCandidate_header_six'] = "Warn Candidate",
        ['manageCandidate_header_seven'] = "Remove Candidate",
        ['manageCandidate_header_eight'] = "Back",
        ['manageCandidate_txt_one'] = "%s",
        ['manageCandidate_txt_two'] = "%s",
        ['manageCandidate_txt_three'] = "%s",
        ['manageCandidate_txt_four'] = "%s",
        ['manageCandidate_txt_five'] = "%s",
        ['manageCandidate_txt_six'] = "Click here to warn the candidate via mail.",
        ['manageCandidate_txt_seven'] = "Click here to remove candidate from the poll.",
        ['manageCandidate_txt_eight'] = "Click here to go back a menu.",

        ['majorOffice_title'] = "Mayor Settings",
        ['majorOffice_header_one'] = "Tax Settings",
        ['majorOffice_header_two'] = "Business Tax Accounts",
        ['majorOffice_header_three'] = "Add/Manage Business",
        ['majorOffice_header_four'] = "City Hall Funds",
        ['majorOffice_header_five'] = "View/Manage Appointments",
        ['majorOffice_header_six'] = "View/Manage Laws",
        ['majorOffice_txt_one'] = "Click here to control the city tax.",
        ['majorOffice_txt_two'] = "Click here too view business tax accounts.",
        ['majorOffice_txt_three'] = "Click here to add/manage a business.",
        ['majorOffice_txt_four'] = "Click here to manage funds.",
        ['majorOffice_txt_five'] = "Click here to view/manage current appointments.",
        ['majorOffice_txt_six'] = "Click here to view/manage laws.",

        ['taxAccounts_title'] = "Tax Accounts",
        ['taxAccounts_header_one'] = "View All Business Accounts",
        ['taxAccounts_header_two'] = "View Unpaid Tax Accounts",
        ['taxAccounts_header_three'] = "Back",
        ['taxAccounts_txt_one'] = "Click here to manage all Business tax accounts.",
        ['taxAccounts_txt_two'] = "Click here to manage unpaid tax accounts.",
        ['taxAccounts_txt_three'] = "Click here to go back to main menu.",

        ['viewallbusinesstax_header_one'] = "Business Accounts",
        ['viewallbusinesstax_header_two'] = "Business Name: %s",
        ['viewallbusinesstax_header_three'] = "Back",
        ['viewallbusinesstax_txt_one'] = "Click here to view this business.",
        ['viewallbusinesstax_txt_two'] = "Click here to go back one menu.",

        ['viewalltaxaccountsnow_title'] = "Account Information",
        ['viewalltaxaccountsnow_state_one'] = "Company Not Registerd",
        ['viewalltaxaccountsnow_state_two'] = "%s",
        ['viewalltaxaccountsnow_header_one'] = "Business Name:",
        ['viewalltaxaccountsnow_header_two'] = "Total Tax Paid",
        ['viewalltaxaccountsnow_header_three'] = "Total Unpaid Tax",
        ['viewalltaxaccountsnow_header_four'] = "Business CEO",
        ['viewalltaxaccountsnow_header_five'] = "Back",
        ['viewalltaxaccountsnow_txt_one'] = "%s",
        ['viewalltaxaccountsnow_txt_two'] = "Amount: $<span style='color:Green;'>%s</span>",
        ['viewalltaxaccountsnow_txt_two_OX'] = "Amount: $%s",
        ['viewalltaxaccountsnow_txt_three_OX'] = "Amount: $%s",
        ['viewalltaxaccountsnow_txt_three'] = "Amount: $<span style='color:Red;'>%s</span>",
        ['viewalltaxaccountsnow_txt_four'] = "Name: %s",
        ['viewalltaxaccountsnow_txt_five'] = "Click to go back one menu.",

        ['viewunpaidtaxaccounts_header_one'] = "Unpaid Tax Accounts",
        ['viewunpaidtaxaccounts_header_two'] = "Business Name: %s",
        ['viewunpaidtaxaccounts_header_three'] = "Back",
        ['viewunpaidtaxaccounts_txt_one'] = "Click here to manage this unpaid tax account.",
        ['viewunpaidtaxaccounts_txt_two'] = "Click here to go back one menu.",

        ['fundsmenu_title'] = "Cityhall Funds",
        ['fundsmenu_header_one'] = "Current Funds Amount:",
        ['fundsmenu_header_two'] = "Withdrawal",
        ['fundsmenu_header_three'] = "Deposit",
        ['fundsmenu_header_four'] = "Back",
        ['fundsmenu_txt_one'] = "Amount: %s%s",
        ['fundsmenu_txt_two'] = "Click here to withdraw funds.",
        ['fundsmenu_txt_three'] = "Click here to deposit funds.",
        ['fundsmenu_txt_four'] = "Click here to go back one menu.",

        ['manageUnpaidTaxAccounts_title'] = "Unpaid Tax Accounts",
        ['manageUnpaidTaxAccounts_state_one'] = "%s",
        ['manageUnpaidTaxAccounts_state_two'] = "Company Not Registerd",
        ['manageUnpaidTaxAccounts_header_one'] = "Business Name:",
        ['manageUnpaidTaxAccounts_header_two'] = "Total Tax Paid",
        ['manageUnpaidTaxAccounts_header_three'] = "Total Unpaid Tax",
        ['manageUnpaidTaxAccounts_header_four'] = "Business CEO",
        ['manageUnpaidTaxAccounts_header_five'] = "Reissue Unpaid Tax Payment",
        ['manageUnpaidTaxAccounts_header_six'] = "Issue Tax Relief",
        ['manageUnpaidTaxAccounts_header_seven'] = "Message Business Owner",
        ['manageUnpaidTaxAccounts_header_eight'] = "Back",
        ['manageUnpaidTaxAccounts_header_nine'] = "Issue Bounty",
        ['manageUnpaidTaxAccounts_txt_one'] = "%s",
        ['manageUnpaidTaxAccounts_txt_two'] = "Amount: $<span style='color:Green;'>%s</span>",
        ['manageUnpaidTaxAccounts_txt_two_OX'] = "Amount: $%s",
        ['manageUnpaidTaxAccounts_txt_three'] = "Amount: $<span style='color:Red;'>%s</span>",
        ['manageUnpaidTaxAccounts_txt_three_OX'] = "Amount: $%s",
        ['manageUnpaidTaxAccounts_txt_four'] = "Name: %s",
        ['manageUnpaidTaxAccounts_txt_five'] = "Click here to take an instant payment of unpaid tax, if the company does not have the funds you should seek a county court judgement.",
        ['manageUnpaidTaxAccounts_txt_six'] = "Click here to clear the companys outstanding tax amount.",
        ['manageUnpaidTaxAccounts_txt_seven'] = "Click here to send a message to the company owner.",
        ['manageUnpaidTaxAccounts_txt_eight'] = "Click to go back one menu.",
        ['manageUnpaidTaxAccounts_txt_nine'] = "Click here to issue a bounty to the owner of the company, doing this will clear there unpaid tax amount.",

        ['taxSettings_header_one'] = "Tax Types",
        ['taxSettings_header_two'] = "%s Tax",
        ['taxSettings_header_three'] = "Back",
        ['taxSettings_txt_one'] = "Click here to manage this tax type.",
        ['taxSettings_txt_two'] = "Click here to go back a menu.",

        ['taxcontrol_title'] = "Tax Management",
        ['taxcontrol_control_percent_one'] = "Current: %s%s",
        ['taxcontrol_control_percent_two'] = "Current: %s%s",
        ['taxcontrol_header_one'] = "Tax Name:",
        ['taxcontrol_header_two'] = "Current Tax %",
        ['taxcontrol_header_three'] = "Change Tax Percent",
        ['taxcontrol_header_four'] = "Back",
        ['taxcontrol_txt_one'] = "%s",
        ['taxcontrol_txt_two'] = "%s",
        ['taxcontrol_txt_three'] = "Click here to change this tax percent for the city.",
        ['taxcontrol_txt_four'] = "Click here to go back a menu.",

        ['registerBusiness_header_one'] = "Add/Manage Business",
        ['registerBusiness_header_two'] = "Name: %s",
        ['registerBusiness_header_three'] = "Back",
        ['registerBusiness_txt_one'] = "Company Name: %s",
        ['registerBusiness_txt_two'] = "Click here to go back a menu.",

        ['registerplayercompany_title'] = "Company Management",
        ['registerplayercompany_header_one'] = "Company Name:",
        ['registerplayercompany_header_two'] = "Transfer Ownership",
        ['registerplayercompany_header_three'] = "Business Grant",
        ['registerplayercompany_header_four'] = "Change Tax Amount",
        ['registerplayercompany_header_five'] = "Register Company",
        ['registerplayercompany_header_six'] = "Back",
        ['registerplayercompany_txt_one'] = "%s",
        ['registerplayercompany_txt_two'] = "Click here to transfer ownership of %s to %s.",
        ['registerplayercompany_txt_three'] = "Click here to issue a grant.",
        ['registerplayercompany_txt_four'] = "Click here to change the amount of tax this company pays.",
        ['registerplayercompany_txt_five'] = "Click here to register %s to the city database.",
        ['registerplayercompany_txt_six'] = "Click here to go back to the register menu.",

        ['appointments_state_two_header_one'] = "Appointment Reason:",
        ['appointments_state_two_header_two'] = "Date & Time:",
        ['appointments_state_two_header_three'] = "Cancel Appointment",
        ['appointments_state_two_txt_one'] = "%s",
        ['appointments_state_two_txt_two'] = "%s",
        ['appointments_state_two_txt_three'] = "Click here to cancel the appointment.",

        ['appointments_state_one_header_one'] = "Appointment Status: [<span style='color:MediumSeaGreen;'>PENDING</span>]",
        ['appointments_state_one_header_one_OX'] = "Appointment Status: PENDING",
        ['appointments_state_one_header_two'] = "Cancel Appointment",
        ['appointments_state_one_txt_one'] = "Your appointment is pending the waiting list, once an appointment has been confirmed your status will change.",
        ['appointments_state_one_txt_two'] = "Click here to cancel the appointment.",

        ['appointments_title'] = "Government Appointments",
        ['appointments_state_zero_header'] = "Arrange Appointment",
        ['appointments_state_zero_txt'] = "Click here to arrange an appointment with the mayor's office.",

        ['appointmentsManage_title'] = "Appointment System",
        ['appointmentsManage_header_one'] = "Requested Appointments",
        ['appointmentsManage_header_two'] = "Scheduled Appointments",
        ['appointmentsManage_header_three'] = "Back",
        ['appointmentsManage_txt_one'] = "Click here to view requested appointments.",
        ['appointmentsManage_txt_two'] = "Click here to view scheduled appointments.",
        ['appointmentsManage_txt_three'] = "Click here to go back to the main menu.",

        ['scheduledAppointments_header_one'] = "Scheduled Appointments",
        ['scheduledAppointments_header_two'] = "Name: %s",
        ['scheduledAppointments_header_three'] = "Back",
        ['scheduledAppointments_txt_one'] = " ",
        ['scheduledAppointments_txt_two'] = "Click here to manage this appointment.",
        ['scheduledAppointments_txt_three'] = "Click here to go back a menu.",

        ['requestedAppointments_header_one'] = "Requested Appointments",
        ['requestedAppointments_header_two'] = "Name: %s",
        ['requestedAppointments_header_three'] = "Back",
        ['requestedAppointments_txt_one'] = " ",
        ['requestedAppointments_txt_two'] = "Click here to manage this appointment request.",
        ['requestedAppointments_txt_three'] = "Click here to go back a menu.",

        ['manageAppointment_setup_title'] = "Appointment Information",
        ['manageAppointment_setup_header_one'] = "Name: %s",
        ['manageAppointment_setup_header_two'] = "Reason:",
        ['manageAppointment_setup_header_three'] = "Issue Appointment",
        ['manageAppointment_setup_header_four'] = "Cancel Appointment",
        ['manageAppointment_setup_header_five'] = "Back",
        ['manageAppointment_setup_txt_one'] = "Issue appointment to set a time and date for this appointment.",
        ['manageAppointment_setup_txt_two'] = "%s",
        ['manageAppointment_setup_txt_three'] = "Click here issue a time and date.",
        ['manageAppointment_setup_txt_four'] = "Click here to cancel this appointment request.",
        ['manageAppointment_setup_txt_five'] = "Click here to go back to the types of appointments.",

        ['manageAppointment_manage_title'] = "Manage Appointment",
        ['manageAppointment_manage_header_one'] = "Name: %s",
        ['manageAppointment_manage_header_two'] = "Reason:",
        ['manageAppointment_manage_header_three'] = "Finish Appointment",
        ['manageAppointment_manage_header_four'] = "Cancel Appointment",
        ['manageAppointment_manage_header_five'] = "Back",
        ['manageAppointment_manage_txt_one'] = "Date & Time: %s",
        ['manageAppointment_manage_txt_two'] = "%s",
        ['manageAppointment_manage_txt_three'] = "Click here to finnish the appointment.",
        ['manageAppointment_manage_txt_four'] = "Click here to cancel this scheduled appointment.",
        ['manageAppointment_manage_txt_five'] = "Click here to go back to the types of appointments.",

        ['grants_title'] = "Company Grants",
        ['grants_header_one'] = "Issue Grant",
        ['grants_header_two'] = "Grant History",
        ['grants_header_three'] = "Back",
        ['grants_txt_one'] = "Click here to issue a grant.",
        ['grants_txt_two'] = "Click here to view the history of grants this business has had.",
        ['grants_txt_three'] = "Click here to go back to the business menu.",

        ['grantHistory_title'] = "Company Grants",
        ['grantHistory_header_one'] = "%s Grant History",
        ['grantHistory_header_two'] = "Date: %s",
        ['grantHistory_header_three'] = "Back",
        ['grantHistory_txt_one'] = "Here you will be able to view all grants that this business has recived from when the company was registard.",
        ['grantHistory_txt_two'] = "Amount: %s%s | Reason Of Grant: %s",
        ['grantHistory_txt_three'] = "Click here to go back a menu.",

        ['staffVotingMenu_title'] = "Staff Voting Management",
        ['staffVotingMenu_header_one'] = "Voting Management",
        ['staffVotingMenu_txt_one'] = "Click here to view the management options.",
    },
    dialog = {
        ['applyDialog_header'] = "Candidate Application",
        ['applyDialog_text_one'] = "Short Description?",
        ['applyDialog_text_two'] = "Why do you want to be a candidate?",
        ['applyDialog_text_three'] = "What would you bring to the city?",

        ['candidateStatus_header'] = "Candidate Denied Application",
        ['candidateStatus_text'] = "Reason for denied application",

        ['withdrawfunds_header'] = "Current Funds: %s%s",
        ['withdrawfunds_text'] = "Amount",

        ['depositfunds_header'] = "Current Funds: %s%s",
        ['depositfunds_text'] = "Amount",

        ['messageOwner_header'] = "Message Owner",
        ['messageOwner_text'] = "Reason",

        ['removeCandidate_header'] = "Remove Candidate",
        ['removeCandidate_text'] = "Reason",

        ['changeTaxCity_header'] = "%s Tax",
        ['changeTaxCity_text'] = "Current: %s%s",

        ['warnCandidate_header'] = "Warn %s",
        ['warnCandidate_text'] = "Warning Reason",

        ['securitychecks_header'] = "Security Checks",
        ['securitychecks_text'] = "pin",

        ['changeplayercompanytax_header'] = "Change Tax Amount",
        ['changeplayercompanytax_text'] = "Current Amount: %s%s",

        ['appointmentReason_header'] = "Arrange Appointment",
        ['appointmentReason_text'] = "Appointment Reason",

        ['issueAppointment_header'] = "Provide Date & Time",
        ['issueAppointment_text_one'] = "Date (02/05/2022)",
        ['issueAppointment_text_two'] = "Time (14:00pm)",

        ['issueGrant_header'] = "City Hall Funds: %s%s",
        ['issueGrant_text_one'] = "Grant Reason",
        ['issueGrant_text_two'] = "Amount ($)",
    }
  },
  ["GER"] = {
    notifications = {
        ['vote_submit'] = "Sie haben Ihre Stimme registriert!",
        ['vote_error'] = "Bitte wählen Sie einen Kandidaten!",
        ['apply_candidate_error'] = "Sie müssen alle Fragen ausfüllen!",
        ['apply_candidate_length_error_one'] = "Kurzbeschreibung darf nicht länger als %s Wörter inklusive Leerzeichen sein!",
        ['apply_candidate_length_error_two'] = "Warum möchten Sie ein Kandidat sein darf nicht länger als %s Wörter inklusive Leerzeichen sein!",
        ['apply_candidate_length_error_three'] = "Was würden Sie zur Stadt beitragen darf nicht länger als %s Wörter inklusive Leerzeichen sein!",
        ['denied_candidate_error'] = "Sie müssen den Grund angeben!",
        ['start_voting_error'] = "Sie können die Kandidatenbewerbungen nur starten, wenn der letzte Wahlsieger seinen Job angetreten hat!",
        ['message_owner_error'] = "Sie müssen den Grund angeben!",
        ['change_city_tax_error_one'] = "Sie müssen einen Betrag unter 1,0 eingeben, z.B. 0,25!",
        ['change_city_tax_error_two'] = "Sie können nicht höher als den gedeckelten Betrag von %s%s gehen",
        ['open_voting_ui_error_one'] = "Sie haben bereits eine Stimme abgegeben.",
        ['open_voting_ui_error_two'] = "Wahlkabinen sind noch nicht zur Verwendung bereit, bitte kommen Sie zurück, wenn die Abstimmung begonnen hat!",
        ['removeCandidate_error'] = "Sie müssen den Grund angeben!",
        ['calcalateTimeClient'] = "%s Tage, %s Stunden und %s Minuten.",
        ['open_law_voting_error'] = "Dieses System wird derzeit von der Regierung aufgebaut. Bitte kommen Sie später wieder.",
    },
    menus = {
        ['applyCandidate_ap_court_title'] = "Bewerbung",
        ['applyCandidate_ap_court_header'] = "Bewerber-App: [<span style='color:Red;'>NICHT BEFUGT</span>]",
        ['applyCandidate_ap_court_header_OX'] = "Bewerber-App: NICHT BEFUGT",
        ['applyCandidate_ap_court_txt'] = "Sie können sich nicht als Kandidat bewerben, da Sie einen Eintrag im Strafregister haben. Sie können sich für diese Position bewerben, wenn Ihr Eintrag gelöscht wird.",
        
        ['applyCandidate_state_six_header'] = "Kandidatenstatus: [<span style='color:Red;'>ENTFERNT</span>]",
        ['applyCandidate_state_six_header_OX'] = "Kandidatenstatus: ENTFERNT",
        ['applyCandidate_state_six_txt'] = "Sie wurden aufgrund von: %s entfernt. Sie können sich erst bei der nächsten Wahl erneut bewerben.",
        
        ['applyCandidate_state_five_header_one'] = "Wahlstatus: [<span style='color:Green;'>GEWINNER</span>]",
        ['applyCandidate_state_five_header_one_OX'] = "Wahlstatus: GEWINNER",
        ['applyCandidate_state_five_header_two'] = "Starte %s Job",
        ['applyCandidate_state_five_txt_one'] = "Herzlichen Glückwunsch, Sie sind der Gewinner und haben die maximale Anzahl von Stimmen erhalten.",
        ['applyCandidate_state_five_txt_two'] = "Klicken Sie hier, um den %s Job anzunehmen.",
        
        ['applyCandidate_state_four_header'] = "Wahlstatus: [<span style='color:Green;'>GESTARTET</span>]",
        ['applyCandidate_state_four_header_OX'] = "Wahlstatus: GESTARTET",
        ['applyCandidate_state_four_txt'] = "Anzahl der Stimmen: <span style='color:Green;'>%s</span>",
        ['applyCandidate_state_four_txt_OX'] = "Anzahl der Stimmen: %s",
        
        ['applyCandidate_state_three_header'] = "Kandidatenstatus: [<span style='color:Green;'>GENEHMIGT</span>]",
        ['applyCandidate_state_three_header_OX'] = "Kandidatenstatus: GENEHMIGT",
        ['applyCandidate_state_three_txt'] = "Ihre Bewerbung wurde genehmigt. Ihre Kandidatur hat nun begonnen. Sie können sich nun in der Öffentlichkeit bewerben, wenn die Abstimmung beginnt.",
        
        ['applyCandidate_state_two_header'] = "Kandidatenstatus: [<span style='color:Red;'>ABGELEHNT</span>]",
        ['applyCandidate_state_two_header_OX'] = "Kandidatenstatus: ABGELEHNT",
        ['applyCandidate_state_two_txt'] = "Vielen Dank für Ihr Interesse, aber Ihre Bewerbung wurde aufgrund von: %s abgelehnt. Sie können sich erst bei der nächsten Wahl erneut bewerben.",
        
        ['applyCandidate_state_one_header'] = "Kandidatenstatus: [<span style='color:Green;'>BEWERBUNG EINGEREICHT</span>]",
        ['applyCandidate_state_one_header_OX'] = "Kandidatenstatus: BEWERBUNG EINGEREICHT",
        ['applyCandidate_state_one_txt'] = "Vielen Dank für Ihre Bewerbung als Kandidat. Ihre Bewerbung wird derzeit von den Regierungsmitarbeitern überprüft.",
        
        ['applyCandidate_state_zero_header_one'] = "Kandidatenbewerbungen: [<span style='color:Green;'>OFFEN</span>]",
        ['applyCandidate_state_zero_header_one_OX'] = "Kandidatenbewerbungen: OFFEN",
        ['applyCandidate_state_zero_header_two'] = "Kandidatenbewerbungen: [<span style='color:Red;'>GESCHLOSSEN</span>]",
        ['applyCandidate_state_zero_header_two_OX'] = "Kandidatenbewerbungen: GESCHLOSSEN",
        ['applyCandidate_state_zero_txt_one'] = "Wenn Sie sich als geeigneter Kandidat betrachten, klicken Sie hier, um sich zu bewerben.",
        ['applyCandidate_state_zero_txt_two'] = "Die Bewerbungen für Kandidaten sind derzeit geschlossen. Bitte achten Sie auf Ankündigungen.",
        
        ['viewRequestedCandidates_header_one'] = "Kandidatenbewerbungen",
        ['viewRequestedCandidates_header_two'] = "Kandidatenname: %s",
        ['viewRequestedCandidates_txt_one'] = " ",
        ['viewRequestedCandidates_txt_two'] = "Klicken Sie hier, um weitere Informationen zu sehen!",
        
        ['getCandidateInfo_title'] = "Kandidateninformationen",
        ['getCandidateInfo_header_one'] = "Kandidatenname",
        ['getCandidateInfo_header_two'] = "Kurzbeschreibung",
        ['getCandidateInfo_header_three'] = "Warum haben Sie sich beworben?",
        ['getCandidateInfo_header_four'] = "Was würden Sie zur Stadt beitragen?",
        ['getCandidateInfo_header_five'] = "Bewerbung akzeptieren",
        ['getCandidateInfo_header_six'] = "Bewerbung ablehnen",
        ['getCandidateInfo_txt_one'] = "%s",
        ['getCandidateInfo_txt_two'] = "%s",
        ['getCandidateInfo_txt_three'] = "%s",
        ['getCandidateInfo_txt_four'] = "%s",
        ['getCandidateInfo_txt_five'] = "Klicken Sie hier, um den Kandidaten zur Kandidatenliste hinzuzufügen.",
        ['getCandidateInfo_txt_six'] = "Klicken Sie hier, um die Bewerbung von %s aus dieser Abstimmung zu entfernen.",
        
        ['startVoting_title'] = "Abstimmungstypen",
        ['startVoting_header'] = "Umfrage: %s",
        ['startVoting_txt'] = "Klicken Sie hier, um die Abstimmung zu starten.",
        
        ['manageCandidate_title'] = "Kandidatenbeschreibung",
        ['manageCandidate_header_one'] = "Kandidatenname:",
        ['manageCandidate_header_two'] = "Kurzbeschreibung",
        ['manageCandidate_header_three'] = "Warum möchten Sie Kandidat sein?",
        ['manageCandidate_header_four'] = "Was würden Sie zur Stadt beitragen?",
        ['manageCandidate_header_five'] = "Aktuelle Stimmen:",
        ['manageCandidate_header_six'] = "Kandidat warnen",
        ['manageCandidate_header_seven'] = "Kandidat entfernen",
        ['manageCandidate_header_eight'] = "Zurück",
        ['manageCandidate_txt_one'] = "%s",
        ['manageCandidate_txt_two'] = "%s",
        ['manageCandidate_txt_three'] = "%s",
        ['manageCandidate_txt_four'] = "%s",
        ['manageCandidate_txt_five'] = "%s",
        ['manageCandidate_txt_six'] = "Klicken Sie hier, um den Kandidaten per E-Mail zu warnen.",
        ['manageCandidate_txt_seven'] = "Klicken Sie hier, um den Kandidaten aus der Abstimmung zu entfernen.",
        ['manageCandidate_txt_eight'] = "Klicken Sie hier, um zum Hauptmenü zurückzukehren.",
        
        ['majorOffice_title'] = "Bürgermeister-Einstellungen",
        ['majorOffice_header_one'] = "Steuereinstellungen",
        ['majorOffice_header_two'] = "Geschäftliche Steuerkonten",
        ['majorOffice_header_three'] = "Geschäft hinzufügen/verwalten",
        ['majorOffice_header_four'] = "Stadthallenfonds",
        ['majorOffice_header_five'] = "Ansichten/Verwalten von Ernennungen",
        ['majorOffice_header_six'] = "Ansichten/Verwalten von Gesetzen",
        ['majorOffice_txt_one'] = "Klicken Sie hier, um die Stadtabgabe zu kontrollieren.",
        ['majorOffice_txt_two'] = "Klicken Sie hier, um geschäftliche Steuerkonten anzuzeigen.",
        ['majorOffice_txt_three'] = "Klicken Sie hier, um ein Geschäft hinzuzufügen/zu verwalten.",
        ['majorOffice_txt_four'] = "Klicken Sie hier, um Fonds zu verwalten.",
        ['majorOffice_txt_five'] = "Klicken Sie hier, um aktuelle Ernennungen anzuzeigen/zu verwalten.",
        ['majorOffice_txt_six'] = "Klicken Sie hier, um Gesetze anzuzeigen/zu verwalten.",
        
        ['taxAccounts_title'] = "Steuerkonten",
        ['taxAccounts_header_one'] = "Alle Geschäftskonten anzeigen",
        ['taxAccounts_header_two'] = "Unbezahlte Steuerkonten anzeigen",
        ['taxAccounts_header_three'] = "Zurück",
        ['taxAccounts_txt_one'] = "Klicken Sie hier, um alle geschäftlichen Steuerkonten zu verwalten.",
        ['taxAccounts_txt_two'] = "Klicken Sie hier, um unbezahlte Steuerkonten zu verwalten.",
        ['taxAccounts_txt_three'] = "Klicken Sie hier, um zum Hauptmenü zurückzukehren.",

        ['viewallbusinesstax_header_one'] = "Unternehmenskonten",
        ['viewallbusinesstax_header_two'] = "Unternehmensname: %s",
        ['viewallbusinesstax_header_three'] = "Zurück",
        ['viewallbusinesstax_txt_one'] = "Klicken Sie hier, um dieses Unternehmen anzuzeigen.",
        ['viewallbusinesstax_txt_two'] = "Klicken Sie hier, um zum vorherigen Menü zurückzukehren.",
        
        ['viewalltaxaccountsnow_title'] = "Kontoinformationen",
        ['viewalltaxaccountsnow_state_one'] = "Unternehmen nicht registriert",
        ['viewalltaxaccountsnow_state_two'] = "%s",
        ['viewalltaxaccountsnow_header_one'] = "Unternehmensname:",
        ['viewalltaxaccountsnow_header_two'] = "Insgesamt gezahlte Steuer",
        ['viewalltaxaccountsnow_header_three'] = "Insgesamt unbezahlte Steuer",
        ['viewalltaxaccountsnow_header_four'] = "Unternehmens-CEO",
        ['viewalltaxaccountsnow_header_five'] = "Zurück",
        ['viewalltaxaccountsnow_txt_one'] = "%s",
        ['viewalltaxaccountsnow_txt_two'] = "Betrag: $<span style='color:Green;'>%s</span>",
        ['viewalltaxaccountsnow_txt_two_OX'] = "Betrag: $%s",
        ['viewalltaxaccountsnow_txt_three_OX'] = "Betrag: $%s",
        ['viewalltaxaccountsnow_txt_three'] = "Betrag: $<span style='color:Red;'>%s</span>",
        ['viewalltaxaccountsnow_txt_four'] = "Name: %s",
        ['viewalltaxaccountsnow_txt_five'] = "Klicken Sie hier, um zum vorherigen Menü zurückzukehren.",
        
        ['viewunpaidtaxaccounts_header_one'] = "Unbezahlte Steuerkonten",
        ['viewunpaidtaxaccounts_header_two'] = "Unternehmensname: %s",
        ['viewunpaidtaxaccounts_header_three'] = "Zurück",
        ['viewunpaidtaxaccounts_txt_one'] = "Klicken Sie hier, um dieses unbezahlte Steuerkonto zu verwalten.",
        ['viewunpaidtaxaccounts_txt_two'] = "Klicken Sie hier, um zum vorherigen Menü zurückzukehren.",
        
        ['fundsmenu_title'] = "Stadthallengelder",
        ['fundsmenu_header_one'] = "Aktueller Geldbetrag:",
        ['fundsmenu_header_two'] = "Abhebung",
        ['fundsmenu_header_three'] = "Einzahlung",
        ['fundsmenu_header_four'] = "Zurück",
        ['fundsmenu_txt_one'] = "Betrag: %s%s",
        ['fundsmenu_txt_two'] = "Klicken Sie hier, um Geld abzuheben.",
        ['fundsmenu_txt_three'] = "Klicken Sie hier, um Geld einzuzahlen.",
        ['fundsmenu_txt_four'] = "Klicken Sie hier, um zum vorherigen Menü zurückzukehren.",
        
        ['manageUnpaidTaxAccounts_title'] = "Unbezahlte Steuerkonten",
        ['manageUnpaidTaxAccounts_state_one'] = "%s",
        ['manageUnpaidTaxAccounts_state_two'] = "Unternehmen nicht registriert",
        ['manageUnpaidTaxAccounts_header_one'] = "Unternehmensname:",
        ['manageUnpaidTaxAccounts_header_two'] = "Insgesamt gezahlte Steuer",
        ['manageUnpaidTaxAccounts_header_three'] = "Insgesamt unbezahlte Steuer",
        ['manageUnpaidTaxAccounts_header_four'] = "Unternehmens-CEO",
        ['manageUnpaidTaxAccounts_header_five'] = "Neuausstellung unbezahlter Steuerzahlung",
        ['manageUnpaidTaxAccounts_header_six'] = "Steuererleichterung ausgeben",
        ['manageUnpaidTaxAccounts_header_seven'] = "Nachricht an Unternehmenseigentümer",
        ['manageUnpaidTaxAccounts_header_eight'] = "Zurück",
        ['manageUnpaidTaxAccounts_header_nine'] = "Bounty ausgeben",
        ['manageUnpaidTaxAccounts_txt_one'] = "%s",
        ['manageUnpaidTaxAccounts_txt_two'] = "Betrag: $<span style='color:Green;'>%s</span>",
        ['manageUnpaidTaxAccounts_txt_two_OX'] = "Betrag: $%s",
        ['manageUnpaidTaxAccounts_txt_three'] = "Betrag: $<span style='color:Red;'>%s</span>",
        ['manageUnpaidTaxAccounts_txt_three_OX'] = "Betrag: $%s",
        ['manageUnpaidTaxAccounts_txt_four'] = "Name: %s",
        ['manageUnpaidTaxAccounts_txt_five'] = "Klicken Sie hier, um sofort eine unbezahlte Steuerzahlung anzufordern. Wenn das Unternehmen nicht über ausreichende Mittel verfügt, sollten Sie eine gerichtliche Entscheidung des Bezirksgerichts suchen.",
        ['manageUnpaidTaxAccounts_txt_six'] = "Klicken Sie hier, um den ausstehenden Steuerbetrag des Unternehmens zu löschen.",
        ['manageUnpaidTaxAccounts_txt_seven'] = "Klicken Sie hier, um dem Unternehmenseigentümer eine Nachricht zu senden.",
        ['manageUnpaidTaxAccounts_txt_eight'] = "Klicken Sie hier, um zum vorherigen Menü zurückzukehren.",
        ['manageUnpaidTaxAccounts_txt_nine'] = "Klicken Sie hier, um dem Eigentümer des Unternehmens einen Bounty auszugeben. Dadurch wird der ausstehende Steuerbetrag beglichen.",
        
        ['taxSettings_header_one'] = "Steuerarten",
        ['taxSettings_header_two'] = "%s Steuer",
        ['taxSettings_header_three'] = "Zurück",
        ['taxSettings_txt_one'] = "Klicken Sie hier, um diese Steuerart zu verwalten.",
        ['taxSettings_txt_two'] = "Klicken Sie hier, um zum vorherigen Menü zurückzukehren.",
        
        ['taxcontrol_title'] = "Steuermanagement",
        ['taxcontrol_control_percent_one'] = "Aktuell: %s%s",
        ['taxcontrol_control_percent_two'] = "Aktuell: %s%s",
        ['taxcontrol_header_one'] = "Steuername:",
        ['taxcontrol_header_two'] = "Aktueller Steuersatz",
        ['taxcontrol_header_three'] = "Steuersatz ändern",
        ['taxcontrol_header_four'] = "Zurück",
        ['taxcontrol_txt_one'] = "%s",
        ['taxcontrol_txt_two'] = "%s",
        ['taxcontrol_txt_three'] = "Klicken Sie hier, um diesen Steuersatz für die Stadt zu ändern.",
        ['taxcontrol_txt_four'] = "Klicken Sie hier, um zum vorherigen Menü zurückzukehren.",
        
        ['registerBusiness_header_one'] = "Unternehmen hinzufügen/verwalten",
        ['registerBusiness_header_two'] = "Name: %s",
        ['registerBusiness_header_three'] = "Zurück",
        ['registerBusiness_txt_one'] = "Unternehmensname: %s",
        ['registerBusiness_txt_two'] = "Klicken Sie hier, um zum vorherigen Menü zurückzukehren.",

        ['registerplayercompany_title'] = "Unternehmensverwaltung",
        ['registerplayercompany_header_one'] = "Unternehmensname:",
        ['registerplayercompany_header_two'] = "Eigentümer übertragen",
        ['registerplayercompany_header_three'] = "Unternehmensförderung",
        ['registerplayercompany_header_four'] = "Steuersatz ändern",
        ['registerplayercompany_header_five'] = "Unternehmen registrieren",
        ['registerplayercompany_header_six'] = "Zurück",
        ['registerplayercompany_txt_one'] = "%s",
        ['registerplayercompany_txt_two'] = "Klicken Sie hier, um die Eigentümerschaft von %s an %s zu übertragen.",
        ['registerplayercompany_txt_three'] = "Klicken Sie hier, um eine Förderung auszustellen.",
        ['registerplayercompany_txt_four'] = "Klicken Sie hier, um den Steuerbetrag dieses Unternehmens zu ändern.",
        ['registerplayercompany_txt_five'] = "Klicken Sie hier, um %s im Stadtdatenbank zu registrieren.",
        ['registerplayercompany_txt_six'] = "Klicken Sie hier, um zum Registrierungsmenü zurückzukehren.",
        
        ['appointments_state_two_header_one'] = "Grund der Ernennung:",
        ['appointments_state_two_header_two'] = "Datum & Uhrzeit:",
        ['appointments_state_two_header_three'] = "Ernennung abbrechen",
        ['appointments_state_two_txt_one'] = "%s",
        ['appointments_state_two_txt_two'] = "%s",
        ['appointments_state_two_txt_three'] = "Klicken Sie hier, um die Ernennung abzubrechen.",
        
        ['appointments_state_one_header_one'] = "Ernennungsstatus: [<span style='color:MediumSeaGreen;'>AUSSTEHEND</span>]",
        ['appointments_state_one_header_one_OX'] = "Ernennungsstatus: AUSSTEHEND",
        ['appointments_state_one_header_two'] = "Ernennung abbrechen",
        ['appointments_state_one_txt_one'] = "Ihre Ernennung steht auf der Warteliste. Sobald eine Ernennung bestätigt wurde, wird Ihr Status geändert.",
        ['appointments_state_one_txt_two'] = "Klicken Sie hier, um die Ernennung abzubrechen.",
        
        ['appointments_title'] = "Regierungs-Ernennungen",
        ['appointments_state_zero_header'] = "Ernennung arrangieren",
        ['appointments_state_zero_txt'] = "Klicken Sie hier, um eine Ernennung mit dem Bürgermeisteramt zu arrangieren.",
        
        ['appointmentsManage_title'] = "Ernennungssystem",
        ['appointmentsManage_header_one'] = "Angeforderte Ernennungen",
        ['appointmentsManage_header_two'] = "Geplante Ernennungen",
        ['appointmentsManage_header_three'] = "Zurück",
        ['appointmentsManage_txt_one'] = "Klicken Sie hier, um angeforderte Ernennungen anzuzeigen.",
        ['appointmentsManage_txt_two'] = "Klicken Sie hier, um geplante Ernennungen anzuzeigen.",
        ['appointmentsManage_txt_three'] = "Klicken Sie hier, um zum Hauptmenü zurückzukehren.",
        
        ['scheduledAppointments_header_one'] = "Geplante Ernennungen",
        ['scheduledAppointments_header_two'] = "Name: %s",
        ['scheduledAppointments_header_three'] = "Zurück",
        ['scheduledAppointments_txt_one'] = " ",
        ['scheduledAppointments_txt_two'] = "Klicken Sie hier, um diese Ernennung zu verwalten.",
        ['scheduledAppointments_txt_three'] = "Klicken Sie hier, um zum vorherigen Menü zurückzukehren.",
        
        ['requestedAppointments_header_one'] = "Angeforderte Ernennungen",
        ['requestedAppointments_header_two'] = "Name: %s",
        ['requestedAppointments_header_three'] = "Zurück",
        ['requestedAppointments_txt_one'] = " ",
        ['requestedAppointments_txt_two'] = "Klicken Sie hier, um diese Ernennungsanfrage zu verwalten.",
        ['requestedAppointments_txt_three'] = "Klicken Sie hier, um zum vorherigen Menü zurückzukehren.",
        
        ['manageAppointment_setup_title'] = "Ernennungsinformationen",
        ['manageAppointment_setup_header_one'] = "Name: %s",
        ['manageAppointment_setup_header_two'] = "Grund:",
        ['manageAppointment_setup_header_three'] = "Ernennung ausstellen",
        ['manageAppointment_setup_header_four'] = "Ernennung abbrechen",
        ['manageAppointment_setup_header_five'] = "Zurück",
        ['manageAppointment_setup_txt_one'] = "Stellen Sie eine Ernennung aus, um Zeit und Datum für diese Ernennung festzulegen.",
        ['manageAppointment_setup_txt_two'] = "%s",
        ['manageAppointment_setup_txt_three'] = "Klicken Sie hier, um Zeit und Datum auszustellen.",
        ['manageAppointment_setup_txt_four'] = "Klicken Sie hier, um diese Ernennungsanfrage abzubrechen.",
        ['manageAppointment_setup_txt_five'] = "Klicken Sie hier, um zu den Arten von Ernennungen zurückzukehren.",
        
        ['manageAppointment_manage_title'] = "Ernennung verwalten",
        ['manageAppointment_manage_header_one'] = "Name: %s",
        ['manageAppointment_manage_header_two'] = "Grund:",
        ['manageAppointment_manage_header_three'] = "Ernennung beenden",
        ['manageAppointment_manage_header_four'] = "Ernennung abbrechen",
        ['manageAppointment_manage_header_five'] = "Zurück",
        ['manageAppointment_manage_txt_one'] = "Datum & Uhrzeit: %s",
        ['manageAppointment_manage_txt_two'] = "%s",
        ['manageAppointment_manage_txt_three'] = "Klicken Sie hier, um die Ernennung zu beenden.",
        ['manageAppointment_manage_txt_four'] = "Klicken Sie hier, um diese geplante Ernennung abzubrechen.",
        ['manageAppointment_manage_txt_five'] = "Klicken Sie hier, um zu den Arten von Ernennungen zurückzukehren.",
        
        ['grants_title'] = "Unternehmensförderungen",
        ['grants_header_one'] = "Förderung ausstellen",
        ['grants_header_two'] = "Förderungshistorie",
        ['grants_header_three'] = "Zurück",
        ['grants_txt_one'] = "Klicken Sie hier, um eine Förderung auszustellen.",
        ['grants_txt_two'] = "Klicken Sie hier, um die Historie der Förderungen dieses Unternehmens anzuzeigen.",
        ['grants_txt_three'] = "Klicken Sie hier, um zum Geschäftsmenü zurückzukehren.",
        
        ['grantHistory_title'] = "Unternehmensförderungen",
        ['grantHistory_header_one'] = "%s Förderungshistorie",
        ['grantHistory_header_two'] = "Datum: %s",
        ['grantHistory_header_three'] = "Zurück",
        ['grantHistory_txt_one'] = "Hier können Sie alle Förderungen einsehen, die dieses Unternehmen seit seiner Registrierung erhalten hat.",
        ['grantHistory_txt_two'] = "Betrag: %s%s | Grund der Förderung: %s",
        ['grantHistory_txt_three'] = "Klicken Sie hier, um zum vorherigen Menü zurückzukehren.",
        
        ['staffVotingMenu_title'] = "Verwaltung der Mitarbeiterabstimmung",
        ['staffVotingMenu_header_one'] = "Abstimmungsverwaltung",
        ['staffVotingMenu_txt_one'] = "Klicken Sie hier, um die Verwaltungsoptionen anzuzeigen.",
            
    },
    dialog = {
        ['applyDialog_header'] = "Bewerbung als Kandidat",
        ['applyDialog_text_one'] = "Kurze Beschreibung?",
        ['applyDialog_text_two'] = "Warum möchten Sie Kandidat werden?",
        ['applyDialog_text_three'] = "Was würden Sie zur Stadt beitragen?",
    
        ['candidateStatus_header'] = "Abgelehnte Kandidatenbewerbung",
        ['candidateStatus_text'] = "Grund für die abgelehnte Bewerbung",
    
        ['withdrawfunds_header'] = "Aktuelle Mittel: %s%s",
        ['withdrawfunds_text'] = "Betrag",
    
        ['depositfunds_header'] = "Aktuelle Mittel: %s%s",
        ['depositfunds_text'] = "Betrag",
    
        ['messageOwner_header'] = "Besitzer kontaktieren",
        ['messageOwner_text'] = "Grund",
    
        ['removeCandidate_header'] = "Kandidaten entfernen",
        ['removeCandidate_text'] = "Grund",
    
        ['changeTaxCity_header'] = "%s Steuer",
        ['changeTaxCity_text'] = "Aktuell: %s%s",
    
        ['warnCandidate_header'] = "%s verwarnen",
        ['warnCandidate_text'] = "Grund für die Verwarnung",
    
        ['securitychecks_header'] = "Sicherheitsprüfungen",
        ['securitychecks_text'] = "PIN",
    
        ['changeplayercompanytax_header'] = "Steuersatz ändern",
        ['changeplayercompanytax_text'] = "Aktueller Betrag: %s%s",
    
        ['appointmentReason_header'] = "Termin vereinbaren",
        ['appointmentReason_text'] = "Grund des Termins",
    
        ['issueAppointment_header'] = "Datum & Uhrzeit festlegen",
        ['issueAppointment_text_one'] = "Datum (02.05.2022)",
        ['issueAppointment_text_two'] = "Uhrzeit (14:00 Uhr)",
    
        ['issueGrant_header'] = "Stadtverwaltungsfonds: %s%s",
        ['issueGrant_text_one'] = "Grund der Förderung",
        ['issueGrant_text_two'] = "Betrag ($)",
    }    
  },
  ["FRA"] = {
    notifications = {
      ['vote_submit'] = "Vous avez enregistré votre vote !",
      ['vote_error'] = "Veuillez choisir un candidat !",
      ['apply_candidate_error'] = "Vous devez remplir toutes les questions !",
      ['apply_candidate_length_error_one'] = "La description courte ne peut pas dépasser %s mots, espaces compris !",
      ['apply_candidate_length_error_two'] = "Pourquoi voulez-vous être candidat ne peut pas dépasser %s mots, espaces compris !",
      ['apply_candidate_length_error_three'] = "Ce que vous apporteriez à la ville ne peut pas dépasser %s mots, espaces compris !",
      ['denied_candidate_error'] = "Vous devez remplir la raison !",
      ['start_voting_error'] = "Vous ne pouvez lancer les candidatures qu'une fois que le gagnant de la dernière élection a réclamé son poste !",
      ['message_owner_error'] = "Vous devez remplir la raison !",
      ['change_city_tax_error_one'] = "Vous devez entrer un montant inférieur à 1, par exemple 0,25 !",
      ['change_city_tax_error_two'] = "Vous ne pouvez pas dépasser le montant plafonné de %s%s",
      ['open_voting_ui_error_one'] = "Vous avez déjà soumis un vote.",
      ['open_voting_ui_error_two'] = "Les isoloirs ne sont pas prêts à être utilisés. Revenez quand le vote aura commencé !",        
      ['removeCandidate_error'] = "Vous devez remplir la raison !",
      ['calcalateTimeClient'] = "%s jours, %s heures et %s minutes.",
      ['open_law_voting_error'] = "Ce système est actuellement en cours de construction par le gouvernement. Veuillez revenir plus tard.",  
    },
    menus = {
      ['applyCandidate_ap_court_title'] = "Candidature",
      ['applyCandidate_ap_court_header'] = "Candidature : [<span style='color:Red;'>NON AUTORISÉ</span>]",
      ['applyCandidate_ap_court_header_OX'] = "Candidature : NON AUTORISÉ",
      ['applyCandidate_ap_court_txt'] = "Vous ne pouvez pas postuler pour devenir candidat, car vous avez un casier judiciaire. Vous pourrez postuler pour ce poste si votre casier est effacé.",
  
      ['applyCandidate_state_six_header'] = "Statut du candidat : [<span style='color:Red;'>RETIRÉ</span>]",
      ['applyCandidate_state_six_header_OX'] = "Statut du candidat : RETIRÉ",
      ['applyCandidate_state_six_txt'] = "Vous avez été retiré en raison de : %s. Vous ne pourrez pas vous représenter avant la prochaine élection.",
  
      ['applyCandidate_state_five_header_one'] = "Statut de vote : [<span style='color:Green;'>VAINQUEUR</span>]",
      ['applyCandidate_state_five_header_one_OX'] = "Statut de vote : VAINQUEUR",
      ['applyCandidate_state_five_header_two'] = "Démarrer le travail de %s",
      ['applyCandidate_state_five_txt_one'] = "Félicitations, vous êtes le vainqueur et avez obtenu le maximum de votes.",
      ['applyCandidate_state_five_txt_two'] = "Cliquez ici pour obtenir le poste de %s.",
  
      ['applyCandidate_state_four_header'] = "Statut de vote : [<span style='color:Green;'>DÉMARRÉ</span>]",
      ['applyCandidate_state_four_header_OX'] = "Statut de vote : DÉMARRÉ",
      ['applyCandidate_state_four_txt'] = "Nombre de votes : <span style='color:Green;'>%s</span>",
      ['applyCandidate_state_four_txt_OX'] = "Nombre de votes : %s",
  
      ['applyCandidate_state_three_header'] = "Statut du candidat : [<span style='color:Green;'>APPROUVÉ</span>]",
      ['applyCandidate_state_three_header_OX'] = "Statut du candidat : APPROUVÉ",
      ['applyCandidate_state_three_txt'] = "Votre candidature a été approuvée, votre candidature a maintenant commencé. Vous pourrez désormais vous faire connaître auprès du public lorsque le scrutin commencera.",
  
      ['applyCandidate_state_two_header'] = "Statut du candidat : [<span style='color:Red;'>REFUSÉ</span>]",
      ['applyCandidate_state_two_header_OX'] = "Statut du candidat : REFUSÉ",
      ['applyCandidate_state_two_txt'] = "Nous vous remercions de votre intérêt, mais votre candidature a été refusée en raison de : %s. Vous ne pourrez pas vous représenter avant la prochaine élection.",
  
      ['applyCandidate_state_one_header'] = "Statut du candidat : [<span style='color:Green;'>EN ATTENTE</span>]",
      ['applyCandidate_state_one_header_OX'] = "Statut du candidat : EN ATTENTE",
      ['applyCandidate_state_one_txt'] = "Merci d'avoir postulé en tant que candidat. Votre candidature est en attente de vérification de la part du personnel gouvernemental.",
  
      ['applyCandidate_state_zero_header_one'] = "Candidatures de candidats : [<span style='color:Green;'>OUVERTES</span>]",
      ['applyCandidate_state_zero_header_one_OX'] = "Candidatures de candidats : OUVERTES",
      ['applyCandidate_state_zero_header_two'] = "Candidatures de candidats : [<span style='color:Red;'>FERMÉES</span>]",
      ['applyCandidate_state_zero_header_two_OX'] = "Candidatures de candidats : FERMÉES",
      ['applyCandidate_state_zero_txt_one'] = "Si vous estimez être un candidat approprié, veuillez cliquer pour postuler.",
      ['applyCandidate_state_zero_txt_two'] = "Les candidatures de candidats sont actuellement fermées. Veuillez surveiller les annonces.",
  
      ['viewRequestedCandidates_header_one'] = "Candidatures de candidats",
      ['viewRequestedCandidates_header_two'] = "Nom du candidat : %s",
      ['viewRequestedCandidates_txt_one'] = " ",
      ['viewRequestedCandidates_txt_two'] = "Cliquez pour voir plus d'informations !",
  
      ['getCandidateInfo_title'] = "Informations sur le candidat",
      ['getCandidateInfo_header_one'] = "Nom du candidat",
      ['getCandidateInfo_header_two'] = "Description courte",
      ['getCandidateInfo_header_three'] = "Pourquoi avez-vous postulé ?",
      ['getCandidateInfo_header_four'] = "Que apporteriez-vous à la ville ?",
      ['getCandidateInfo_header_five'] = "Accepter la candidature",
      ['getCandidateInfo_header_six'] = "Refuser la candidature",
      ['getCandidateInfo_txt_one'] = "%s",
      ['getCandidateInfo_txt_two'] = "%s",
      ['getCandidateInfo_txt_three'] = "%s",
      ['getCandidateInfo_txt_four'] = "%s",
      ['getCandidateInfo_txt_five'] = "Cliquez ici pour ajouter le candidat à la liste des candidatures.",
      ['getCandidateInfo_txt_six'] = "Cliquez ici pour supprimer la candidature de %s de ce scrutin.",
  
      ['startVoting_title'] = "Types de vote",
      ['startVoting_header'] = "Sondage : %s",
      ['startVoting_txt'] = "Cliquez ici pour démarrer le vote.",
  
      ['manageCandidate_title'] = "Description du Candidat",
      ['manageCandidate_header_one'] = "Nom du Candidat :",
      ['manageCandidate_header_two'] = "Description Courte :",
      ['manageCandidate_header_three'] = "Pourquoi voulez-vous être candidat ?",
      ['manageCandidate_header_four'] = "Que apporterez-vous à la ville ?",
      ['manageCandidate_header_five'] = "Votes Actuels :",
      ['manageCandidate_header_six'] = "Avertir le Candidat",
      ['manageCandidate_header_seven'] = "Supprimer le Candidat",
      ['manageCandidate_header_eight'] = "Retour",
      ['manageCandidate_txt_one'] = "%s",
      ['manageCandidate_txt_two'] = "%s",
      ['manageCandidate_txt_three'] = "%s",
      ['manageCandidate_txt_four'] = "%s",
      ['manageCandidate_txt_five'] = "%s",
      ['manageCandidate_txt_six'] = "Cliquez ici pour avertir le candidat par email.",
      ['manageCandidate_txt_seven'] = "Cliquez ici pour supprimer le candidat du sondage.",
      ['manageCandidate_txt_eight'] = "Cliquez ici pour revenir au menu précédent.",
      
      ['majorOffice_title'] = "Paramètres du Maire",
      ['majorOffice_header_one'] = "Paramètres des Taxes",
      ['majorOffice_header_two'] = "Comptes de Taxe des Entreprises",
      ['majorOffice_header_three'] = "Ajouter/Gérer une Entreprise",
      ['majorOffice_header_four'] = "Fonds de la Mairie",
      ['majorOffice_header_five'] = "Voir/Gérer les Nominations",
      ['majorOffice_header_six'] = "Voir/Gérer les Lois",
      ['majorOffice_txt_one'] = "Cliquez ici pour contrôler les taxes de la ville.",
      ['majorOffice_txt_two'] = "Cliquez ici pour voir les comptes de taxe des entreprises.",
      ['majorOffice_txt_three'] = "Cliquez ici pour ajouter/gérer une entreprise.",
      ['majorOffice_txt_four'] = "Cliquez ici pour gérer les fonds.",
      ['majorOffice_txt_five'] = "Cliquez ici pour voir/gérer les nominations actuelles.",
      ['majorOffice_txt_six'] = "Cliquez ici pour voir/gérer les lois.",
      
      ['taxAccounts_title'] = "Comptes de Taxes",
      ['taxAccounts_header_one'] = "Voir Tous les Comptes d'Entreprises",
      ['taxAccounts_header_two'] = "Voir les Comptes de Taxes Impayées",
      ['taxAccounts_header_three'] = "Retour",
      ['taxAccounts_txt_one'] = "Cliquez ici pour gérer tous les comptes de taxe d'entreprise.",
      ['taxAccounts_txt_two'] = "Cliquez ici pour gérer les comptes de taxes impayées.",
      ['taxAccounts_txt_three'] = "Cliquez ici pour revenir au menu principal.",
      
      ['viewallbusinesstax_header_one'] = "Comptes d'Entreprise",
      ['viewallbusinesstax_header_two'] = "Nom de l'Entreprise : %s",
      ['viewallbusinesstax_header_three'] = "Retour",
      ['viewallbusinesstax_txt_one'] = "Cliquez ici pour voir cette entreprise.",
      ['viewallbusinesstax_txt_two'] = "Cliquez ici pour retourner au menu précédent.",
      
      ['viewalltaxaccountsnow_title'] = "Informations du Compte",
      ['viewalltaxaccountsnow_state_one'] = "Entreprise non enregistrée",
      ['viewalltaxaccountsnow_state_two'] = "%s",
      ['viewalltaxaccountsnow_header_one'] = "Nom de l'Entreprise :",
      ['viewalltaxaccountsnow_header_two'] = "Total des Taxes Payées",
      ['viewalltaxaccountsnow_header_three'] = "Total des Taxes Impayées",
      ['viewalltaxaccountsnow_header_four'] = "PDG de l'Entreprise",
      ['viewalltaxaccountsnow_header_five'] = "Retour",
      ['viewalltaxaccountsnow_txt_one'] = "%s",
      ['viewalltaxaccountsnow_txt_two'] = "Montant : $<span style='color:Green;'>%s</span>",
      ['viewalltaxaccountsnow_txt_two_OX'] = "Montant : $%s",
      ['viewalltaxaccountsnow_txt_three_OX'] = "Montant : $%s",
      ['viewalltaxaccountsnow_txt_three'] = "Montant : $<span style='color:Red;'>%s</span>",
      ['viewalltaxaccountsnow_txt_four'] = "Nom : %s",
      ['viewalltaxaccountsnow_txt_five'] = "Cliquez pour revenir au menu précédent.",
      
      ['viewunpaidtaxaccounts_header_one'] = "Comptes de Taxes Impayées",
      ['viewunpaidtaxaccounts_header_two'] = "Nom de l'Entreprise : %s",
      ['viewunpaidtaxaccounts_header_three'] = "Retour",
      ['viewunpaidtaxaccounts_txt_one'] = "Cliquez ici pour gérer ce compte de taxes impayées.",
      ['viewunpaidtaxaccounts_txt_two'] = "Cliquez ici pour revenir au menu précédent.",
      
      ['fundsmenu_title'] = "Fonds de la Mairie",
      ['fundsmenu_header_one'] = "Montant Actuel des Fonds :",
      ['fundsmenu_header_two'] = "Retrait",
      ['fundsmenu_header_three'] = "Dépôt",
      ['fundsmenu_header_four'] = "Retour",
      ['fundsmenu_txt_one'] = "Montant : %s%s",
      ['fundsmenu_txt_two'] = "Cliquez ici pour retirer des fonds.",
      ['fundsmenu_txt_three'] = "Cliquez ici pour déposer des fonds.",
      ['fundsmenu_txt_four'] = "Cliquez ici pour revenir au menu précédent.",
      
      ['manageUnpaidTaxAccounts_title'] = "Comptes de Taxes Impayées",
      ['manageUnpaidTaxAccounts_state_one'] = "%s",
      ['manageUnpaidTaxAccounts_state_two'] = "Entreprise Non Enregistrée",
      ['manageUnpaidTaxAccounts_header_one'] = "Nom de l'Entreprise :",
      ['manageUnpaidTaxAccounts_header_two'] = "Total des Taxes Payées",
      ['manageUnpaidTaxAccounts_header_three'] = "Total des Taxes Impayées",
      ['manageUnpaidTaxAccounts_header_four'] = "PDG de l'Entreprise",
      ['manageUnpaidTaxAccounts_header_five'] = "Réémettre le Paiement de Taxe Impayée",
      ['manageUnpaidTaxAccounts_header_six'] = "Émettre une Réduction d'Impôt",
      ['manageUnpaidTaxAccounts_header_seven'] = "Envoyer un Message au Propriétaire de l'Entreprise",
      ['manageUnpaidTaxAccounts_header_eight'] = "Retour",
      ['manageUnpaidTaxAccounts_header_nine'] = "Émettre une Prime",
      ['manageUnpaidTaxAccounts_txt_one'] = "%s",
      ['manageUnpaidTaxAccounts_txt_two'] = "Montant : $<span style='color:Green;'>%s</span>",
      ['manageUnpaidTaxAccounts_txt_two_OX'] = "Montant : $%s",
      ['manageUnpaidTaxAccounts_txt_three'] = "Montant : $<span style='color:Red;'>%s</span>",
      ['manageUnpaidTaxAccounts_txt_three_OX'] = "Montant : $%s",
      ['manageUnpaidTaxAccounts_txt_four'] = "Nom : %s",
      ['manageUnpaidTaxAccounts_txt_five'] = "Cliquez ici pour effectuer un paiement immédiat de taxes impayées. Si l'entreprise n'a pas les fonds nécessaires, vous devriez engager une procédure judiciaire.",
      ['manageUnpaidTaxAccounts_txt_six'] = "Cliquez ici pour effacer le montant des taxes impayées de l'entreprise.",
      ['manageUnpaidTaxAccounts_txt_seven'] = "Cliquez ici pour envoyer un message au propriétaire de l'entreprise.",
      ['manageUnpaidTaxAccounts_txt_eight'] = "Cliquez ici pour revenir au menu précédent.",
      ['manageUnpaidTaxAccounts_txt_nine'] = "Cliquez ici pour émettre une prime au propriétaire de l'entreprise. Cela effacera leur montant de taxes impayées.",
      
      ['taxSettings_header_one'] = "Types de Taxes",
      ['taxSettings_header_two'] = "Taxe %s",
      ['taxSettings_header_three'] = "Retour",
      ['taxSettings_txt_one'] = "Cliquez ici pour gérer ce type de taxe.",
      ['taxSettings_txt_two'] = "Cliquez ici pour revenir au menu précédent.",
      
      ['taxcontrol_title'] = "Gestion des Taxes",
      ['taxcontrol_control_percent_one'] = "Actuel : %s%s",
      ['taxcontrol_control_percent_two'] = "Actuel : %s%s",
      ['taxcontrol_header_one'] = "Nom de la Taxe :",
      ['taxcontrol_header_two'] = "Taux de Taxe Actuel",
      ['taxcontrol_header_three'] = "Modifier le Taux de Taxe",
      ['taxcontrol_header_four'] = "Retour",
      ['taxcontrol_txt_one'] = "%s",
      ['taxcontrol_txt_two'] = "%s",
      ['taxcontrol_txt_three'] = "Cliquez ici pour modifier ce taux de taxe pour la ville.",
      ['taxcontrol_txt_four'] = "Cliquez ici pour revenir au menu précédent.",
      
      ['registerBusiness_header_one'] = "Ajouter/Gérer une Entreprise",
      ['registerBusiness_header_two'] = "Nom : %s",
      ['registerBusiness_header_three'] = "Retour",
      ['registerBusiness_txt_one'] = "Nom de l'Entreprise : %s",
      ['registerBusiness_txt_two'] = "Cliquez ici pour revenir au menu précédent.",
      
      ['registerplayercompany_title'] = "Gestion de l'Entreprise",
      ['registerplayercompany_header_one'] = "Nom de l'Entreprise :",
      ['registerplayercompany_header_two'] = "Transférer la Propriété",
      ['registerplayercompany_header_three'] = "Subvention d'Entreprise",
      ['registerplayercompany_header_four'] = "Modifier le Montant de Taxe",
      ['registerplayercompany_header_five'] = "Enregistrer l'Entreprise",
      ['registerplayercompany_header_six'] = "Retour",
      ['registerplayercompany_txt_one'] = "%s",
      ['registerplayercompany_txt_two'] = "Cliquez ici pour transférer la propriété de %s à %s.",
      ['registerplayercompany_txt_three'] = "Cliquez ici pour émettre une subvention.",
      ['registerplayercompany_txt_four'] = "Cliquez ici pour modifier le montant de taxe que paie cette entreprise.",
      ['registerplayercompany_txt_five'] = "Cliquez ici pour enregistrer %s dans la base de données de la ville.",
      ['registerplayercompany_txt_six'] = "Cliquez ici pour revenir au menu d'enregistrement.",
      
      ['appointments_state_two_header_one'] = "Raison du Rendez-vous :",
      ['appointments_state_two_header_two'] = "Date & Heure :",
      ['appointments_state_two_header_three'] = "Annuler le Rendez-vous",
      ['appointments_state_two_txt_one'] = "%s",
      ['appointments_state_two_txt_two'] = "%s",
      ['appointments_state_two_txt_three'] = "Cliquez ici pour annuler le rendez-vous.",
      
      ['appointments_state_one_header_one'] = "Statut du Rendez-vous : [<span style='color:MediumSeaGreen;'>EN ATTENTE</span>]",
      ['appointments_state_one_header_one_OX'] = "Statut du Rendez-vous : EN ATTENTE",
      ['appointments_state_one_header_two'] = "Annuler le Rendez-vous",
      ['appointments_state_one_txt_one'] = "Votre rendez-vous est en attente sur la liste d'attente. Une fois que le rendez-vous sera confirmé, votre statut changera.",
      ['appointments_state_one_txt_two'] = "Cliquez ici pour annuler le rendez-vous.",
      
      ['appointments_title'] = "Rendez-vous Gouvernementaux",
      ['appointments_state_zero_header'] = "Organiser un Rendez-vous",
      ['appointments_state_zero_txt'] = "Cliquez ici pour organiser un rendez-vous avec le bureau du maire.",
      
      ['appointmentsManage_title'] = "Système de Rendez-vous",
      ['appointmentsManage_header_one'] = "Rendez-vous Demandés",
      ['appointmentsManage_header_two'] = "Rendez-vous Planifiés",
      ['appointmentsManage_header_three'] = "Retour",
      ['appointmentsManage_txt_one'] = "Cliquez ici pour voir les rendez-vous demandés.",
      ['appointmentsManage_txt_two'] = "Cliquez ici pour voir les rendez-vous planifiés.",
      ['appointmentsManage_txt_three'] = "Cliquez ici pour revenir au menu principal.",
      
      ['scheduledAppointments_header_one'] = "Rendez-vous Planifiés",
      ['scheduledAppointments_header_two'] = "Nom : %s",
      ['scheduledAppointments_header_three'] = "Retour",
      ['scheduledAppointments_txt_one'] = " ",
      ['scheduledAppointments_txt_two'] = "Cliquez ici pour gérer ce rendez-vous.",
      ['scheduledAppointments_txt_three'] = "Cliquez ici pour revenir à un menu.",
      
      ['requestedAppointments_header_one'] = "Rendez-vous Demandés",
      ['requestedAppointments_header_two'] = "Nom : %s",
      ['requestedAppointments_header_three'] = "Retour",
      ['requestedAppointments_txt_one'] = " ",
      ['requestedAppointments_txt_two'] = "Cliquez ici pour gérer cette demande de rendez-vous.",
      ['requestedAppointments_txt_three'] = "Cliquez ici pour revenir à un menu.",
      
      ['manageAppointment_setup_title'] = "Informations sur le Rendez-vous",
      ['manageAppointment_setup_header_one'] = "Nom : %s",
      ['manageAppointment_setup_header_two'] = "Raison :",
      ['manageAppointment_setup_header_three'] = "Créer un Rendez-vous",
      ['manageAppointment_setup_header_four'] = "Annuler le Rendez-vous",
      ['manageAppointment_setup_header_five'] = "Retour",
      ['manageAppointment_setup_txt_one'] = "Créez un rendez-vous pour fixer une date et une heure pour ce rendez-vous.",
      ['manageAppointment_setup_txt_two'] = "%s",
      ['manageAppointment_setup_txt_three'] = "Cliquez ici pour fixer une date et une heure.",
      ['manageAppointment_setup_txt_four'] = "Cliquez ici pour annuler cette demande de rendez-vous.",
      ['manageAppointment_setup_txt_five'] = "Cliquez ici pour revenir aux types de rendez-vous.",
      
      ['manageAppointment_manage_title'] = "Gérer le Rendez-vous",
      ['manageAppointment_manage_header_one'] = "Nom : %s",
      ['manageAppointment_manage_header_two'] = "Raison :",
      ['manageAppointment_manage_header_three'] = "Terminer le Rendez-vous",
      ['manageAppointment_manage_header_four'] = "Annuler le Rendez-vous",
      ['manageAppointment_manage_header_five'] = "Retour",
      ['manageAppointment_manage_txt_one'] = "Date & Heure : %s",
      ['manageAppointment_manage_txt_two'] = "%s",
      ['manageAppointment_manage_txt_three'] = "Cliquez ici pour terminer le rendez-vous.",
      ['manageAppointment_manage_txt_four'] = "Cliquez ici pour annuler ce rendez-vous planifié.",
      ['manageAppointment_manage_txt_five'] = "Cliquez ici pour revenir aux types de rendez-vous.",
      
      ['grants_title'] = "Subventions d'Entreprise",
      ['grants_header_one'] = "Attribuer une Subvention",
      ['grants_header_two'] = "Historique des Subventions",
      ['grants_header_three'] = "Retour",
      ['grants_txt_one'] = "Cliquez ici pour attribuer une subvention.",
      ['grants_txt_two'] = "Cliquez ici pour voir l'historique des subventions reçues par cette entreprise.",
      ['grants_txt_three'] = "Cliquez ici pour revenir au menu de l'entreprise.",
      
      ['grantHistory_title'] = "Historique des Subventions d'Entreprise",
      ['grantHistory_header_one'] = "Historique des Subventions de %s",
      ['grantHistory_header_two'] = "Date : %s",
      ['grantHistory_header_three'] = "Retour",
      ['grantHistory_txt_one'] = "Ici, vous pourrez voir toutes les subventions que cette entreprise a reçues depuis son enregistrement.",
      ['grantHistory_txt_two'] = "Montant : %s%s | Raison de la Subvention : %s",
      ['grantHistory_txt_three'] = "Cliquez ici pour revenir à un menu.",
      
      ['staffVotingMenu_title'] = "Gestion des Votes du Personnel",
      ['staffVotingMenu_header_one'] = "Gestion des Votes",
      ['staffVotingMenu_txt_one'] = "Cliquez ici pour voir les options de gestion.",                          
    },
    dialog = {
      ['applyDialog_header'] = "Candidature du Candidat",
      ['applyDialog_text_one'] = "Brève description ?",
      ['applyDialog_text_two'] = "Pourquoi voulez-vous être candidat ?",
      ['applyDialog_text_three'] = "Que apporteriez-vous à la ville ?",

      ['candidateStatus_header'] = "Candidature du Candidat Refusée",
      ['candidateStatus_text'] = "Raison du refus de la candidature",

      ['withdrawfunds_header'] = "Fonds Actuels : %s%s",
      ['withdrawfunds_text'] = "Montant",

      ['depositfunds_header'] = "Fonds Actuels : %s%s",
      ['depositfunds_text'] = "Montant",

      ['messageOwner_header'] = "Message au Propriétaire",
      ['messageOwner_text'] = "Raison",

      ['removeCandidate_header'] = "Retirer le Candidat",
      ['removeCandidate_text'] = "Raison",

      ['changeTaxCity_header'] = "Taxe de %s",
      ['changeTaxCity_text'] = "Actuelle : %s%s",

      ['warnCandidate_header'] = "Avertir %s",
      ['warnCandidate_text'] = "Raison de l'avertissement",

      ['securitychecks_header'] = "Vérifications de Sécurité",
      ['securitychecks_text'] = "code PIN",

      ['changeplayercompanytax_header'] = "Modifier le Montant de la Taxe",
      ['changeplayercompanytax_text'] = "Montant Actuel : %s%s",

      ['appointmentReason_header'] = "Organiser un Rendez-vous",
      ['appointmentReason_text'] = "Raison du Rendez-vous",

      ['issueAppointment_header'] = "Indiquer la Date et l'Heure",
      ['issueAppointment_text_one'] = "Date (02/05/2022)",
      ['issueAppointment_text_two'] = "Heure (14h00)",

      ['issueGrant_header'] = "Fonds de l'Hôtel de Ville : %s%s",
      ['issueGrant_text_one'] = "Raison de la Subvention",
      ['issueGrant_text_two'] = "Montant ($)",
    }
  }
}

LangServer = {
  ["ENG"] = {
    notifications = {
        ['candidateStatus_one'] = "Your candidacy application has been accepted.",
        ['candidateStatus_two'] = "Your candidacy application has been denied, Visit the court house for the reason why.",
        
        ['startVoting'] = "The government has started the candidate application process, please visit the townhall to apply.",
        
        ['applyDialog'] = "%s",

        ['enableVoting_one'] = "Candidate applications are now closed and the voting poll are now open, come down to the townhall to vote for your candidate.",
        ['enableVoting_two'] = "You can only start the voting if there are canidates.",
        
        ['finishVoting_one'] = "You have gave the verdict, the winner has been notified via email.",
        ['finishVoting_two'] = "You can only finish the voting if there are canidates.",

        ['takeFullPayment_one'] = "Business: %s has cleared the unpaid tax on there account.",
        ['takeFullPayment_two'] = "Business: %s does not have the funds to clear there debt.",

        ['clearUnpaidTax'] = "Business: %s has been given tax relief.",

        ['systemTax'] = "You have paid %s%s income tax.",

        ['businessTaxPayments_one'] = "Your business could not afford the business tax payment of %s%s.",
        ['businessTaxPayments_two'] = "Your business has paid %s%s in tax.",

        ['changeTaxCity'] = "You have updated %s Tax to %s%s",

        ['chargeCityTax'] = "You have paid %s%s %s tax.",

        ['warnCandidate'] = "You have been warned by the voting staff, check the email for more info.",

        ['removeCandidate'] = "You have removed %s as a candidate.",

        ['sortfunds_one'] = "You do not have the correct funds to withdraw.",
        ['sortfunds_two'] = "You are not allowed to withdraw less then %s%s",
        ['sortfunds_three'] = "You are not allowed to withdraw more then %s%s",
        ['sortfunds_four'] = "You have withdrawn %s%s from the cityhall funds",
        ['sortfunds_five'] = "You do not have the correct funds to deposit.",
        ['sortfunds_six'] = "You are not allowed to deposit less then %s%s",
        ['sortfunds_seven'] = "You are not allowed to deposit more then %s%s",
        ['sortfunds_eight'] = "You have deposit %s%s to the cityhall funds",

        ['verifyPin'] = "Security pin email sent to %s.",
        
        ['registerplayercompany'] = "you have registerd %s to the city database.",

        ['transferplayercompany_one'] = "you have transferd ownership of %s to %s.",
        ['transferplayercompany_two'] = "This company is a government owned company and can't be transferred.",

        ['changeplayercompanytax_one'] = "You can not set the tax amount higher then the legal amount!",
        ['changeplayercompanytax_two'] = "You can not set the tax amount lower then the legal amount!",
        ['changeplayercompanytax_three'] = "You have change the companys tax from %s to %s.",

        ['messageOwner'] = "You have been sent an email from the mayor's office.",

        ['submitAppointment'] = "Your appointment request has been sent.",

        ['cancelAppointment'] = "Your appointment has been cancelled.",

        ['mayorCancelAppointment'] = "You have cancelled %s appointment.",

        ['issueAppointment'] = "You have scheduled an appointment for %s on %s, an email has been sent with the date and time.",
        
        ['finishAppointment'] = "You have marked this appointment as finished.",

        ['issueGrant_one'] = "The cityhall does not have enough funds to cover this grant.",
        ['issueGrant_two'] = "The cityhall can only grant from %s%s to %s%s.",
        ['issueGrant_three'] = "The cityhall has issued a grant of %s%s to %s.",
        ['issueGrant_four'] = "The cityhall has issued a grant of %s%s to %s.",

        ['BountySet'] = "You have issued a bounty on %s as his company has failed to pay the unpaid tax.",

        ['removedPassedLaw'] = "You have removed a passed law: %s, this law has now been deleted from the government database.",
        ['newLawVoting'] = "You have created a new law: %s, the voting to this will end in %s.",
        ['updateVotingDB_one'] = "Your vote for %s has been submitted, you have voted for the law to pass.",
        ['updateVotingDB_two'] = "Your vote for %s has been submitted, you have voted against the law.",
        ['calcalateTime'] = "%s days, %s hours, and %s minutes.",
        ['candidateRemove'] = "You have removed %s from the voting poll.",
        ['warnCandidateNew'] = "You have sent a warning to %s.",
        
    }
  },
  ["GER"] = {
    notifications = {
        ['candidateStatus_one'] = "Ihre Kandidatur wurde angenommen.",
        ['candidateStatus_two'] = "Ihre Kandidatur wurde abgelehnt. Besuchen Sie das Gerichtsgebäude, um den Grund zu erfahren.",
        
        ['startVoting'] = "Die Regierung hat den Kandidatenbewerbungsprozess gestartet. Bitte besuchen Sie das Rathaus, um sich zu bewerben.",
        
        ['applyDialog'] = "%s",
    
        ['enableVoting_one'] = "Die Bewerbungen für Kandidaten sind jetzt geschlossen, und die Abstimmungsumfrage ist eröffnet. Besuchen Sie das Rathaus, um für Ihren Kandidaten zu stimmen.",
        ['enableVoting_two'] = "Sie können die Abstimmung nur starten, wenn es Kandidaten gibt.",
        
        ['finishVoting_one'] = "Sie haben das Urteil gefällt. Der Gewinner wurde per E-Mail benachrichtigt.",
        ['finishVoting_two'] = "Sie können die Abstimmung nur beenden, wenn es Kandidaten gibt.",
    
        ['takeFullPayment_one'] = "Unternehmen: %s hat die unbezahlte Steuer auf ihrem Konto beglichen.",
        ['takeFullPayment_two'] = "Unternehmen: %s hat nicht genug Geld, um ihre Schulden zu begleichen.",
    
        ['clearUnpaidTax'] = "Unternehmen: %s wurde Steuererleichterung gewährt.",
    
        ['systemTax'] = "Sie haben %s%s Einkommensteuer bezahlt.",
    
        ['businessTaxPayments_one'] = "Ihr Unternehmen konnte die Geschäftssteuerzahlung von %s%s nicht leisten.",
        ['businessTaxPayments_two'] = "Ihr Unternehmen hat %s%s an Steuern gezahlt.",
    
        ['changeTaxCity'] = "Sie haben die %s Steuer auf %s%s aktualisiert.",
    
        ['chargeCityTax'] = "Sie haben %s%s %s Steuer bezahlt.",
    
        ['warnCandidate'] = "Sie wurden vom Abstimmungspersonal verwarnt. Überprüfen Sie die E-Mail für weitere Informationen.",
    
        ['removeCandidate'] = "Sie haben %s als Kandidat entfernt.",
    
        ['sortfunds_one'] = "Sie haben nicht genügend Geld, um abzuheben.",
        ['sortfunds_two'] = "Sie dürfen nicht weniger als %s%s abheben.",
        ['sortfunds_three'] = "Sie dürfen nicht mehr als %s%s abheben.",
        ['sortfunds_four'] = "Sie haben %s%s aus den Stadtverwaltungsfonds abgehoben.",
        ['sortfunds_five'] = "Sie haben nicht genügend Geld, um einzuzahlen.",
        ['sortfunds_six'] = "Sie dürfen nicht weniger als %s%s einzahlen.",
        ['sortfunds_seven'] = "Sie dürfen nicht mehr als %s%s einzahlen.",
        ['sortfunds_eight'] = "Sie haben %s%s auf die Stadtverwaltungsfonds eingezahlt.",
    
        ['verifyPin'] = "Sicherheits-PIN-E-Mail an %s gesendet.",
        
        ['registerplayercompany'] = "Sie haben %s in der Stadtdatenbank registriert.",
    
        ['transferplayercompany_one'] = "Sie haben das Eigentum von %s auf %s übertragen.",
        ['transferplayercompany_two'] = "Dieses Unternehmen ist ein staatliches Unternehmen und kann nicht übertragen werden.",
    
        ['changeplayercompanytax_one'] = "Sie können den Steuerbetrag nicht höher als den gesetzlichen Betrag festlegen!",
        ['changeplayercompanytax_two'] = "Sie können den Steuerbetrag nicht niedriger als den gesetzlichen Betrag festlegen!",
        ['changeplayercompanytax_three'] = "Sie haben die Unternehmenssteuer von %s auf %s geändert.",
    
        ['messageOwner'] = "Sie haben eine E-Mail vom Büro des Bürgermeisters erhalten.",
    
        ['submitAppointment'] = "Ihr Terminantrag wurde gesendet.",
    
        ['cancelAppointment'] = "Ihr Termin wurde abgesagt.",
    
        ['mayorCancelAppointment'] = "Sie haben den Termin von %s abgesagt.",
    
        ['issueAppointment'] = "Sie haben einen Termin für %s am %s geplant. Eine E-Mail mit Datum und Uhrzeit wurde gesendet.",
        
        ['finishAppointment'] = "Sie haben diesen Termin als abgeschlossen markiert.",
    
        ['issueGrant_one'] = "Das Rathaus hat nicht genug Geld, um diese Förderung zu decken.",
        ['issueGrant_two'] = "Das Rathaus kann nur von %s%s bis %s%s gewähren.",
        ['issueGrant_three'] = "Das Rathaus hat eine Förderung von %s%s an %s vergeben.",
        ['issueGrant_four'] = "Das Rathaus hat eine Förderung von %s%s an %s vergeben.",
    
        ['BountySet'] = "Sie haben eine Prämie auf %s ausgesetzt, da sein Unternehmen die unbezahlte Steuer nicht beglichen hat.",

        ['removedPassedLaw'] = "Sie haben ein verabschiedetes Gesetz entfernt: %s, dieses Gesetz wurde nun aus der Regierungsdatenbank gelöscht.",
        ['newLawVoting'] = "Sie haben ein neues Gesetz erstellt: %s, die Abstimmung dazu endet in %s.",
        ['updateVotingDB_one'] = "Ihre Stimme für %s wurde abgegeben, Sie haben für das Gesetz gestimmt, dass es angenommen wird.",
        ['updateVotingDB_two'] = "Ihre Stimme für %s wurde abgegeben, Sie haben gegen das Gesetz gestimmt.",
        ['calcalateTime'] = "%s Tage, %s Stunden und %s Minuten.",
        ['candidateRemove'] = "Sie haben %s aus der Abstimmung entfernt.",
        ['warnCandidateNew'] = "Sie haben %s eine Warnung geschickt.",    
    }  
  },
  ["FRA"] = {
    notifications = {
      ['candidateStatus_one'] = "Votre candidature a été acceptée.",
      ['candidateStatus_two'] = "Votre candidature a été refusée. Rendez-vous à la mairie pour connaître la raison.",
  
      ['startVoting'] = "Le gouvernement a commencé le processus de candidature. Veuillez vous rendre à la mairie pour postuler.",
  
      ['applyDialog'] = "%s",
  
      ['enableVoting_one'] = "Les candidatures sont désormais closes et le scrutin est ouvert. Venez à la mairie pour voter pour votre candidat.",
      ['enableVoting_two'] = "Vous ne pouvez lancer le vote que s'il y a des candidats.",
  
      ['finishVoting_one'] = "Vous avez donné votre verdict, le gagnant a été informé par e-mail.",
      ['finishVoting_two'] = "Vous ne pouvez terminer le vote que s'il y a des candidats.",
  
      ['takeFullPayment_one'] = "Entreprise : %s a réglé les impôts impayés sur son compte.",
      ['takeFullPayment_two'] = "L'entreprise : %s n'a pas les fonds nécessaires pour rembourser sa dette.",
  
      ['clearUnpaidTax'] = "Entreprise : %s a bénéficié d'une réduction d'impôt.",
  
      ['systemTax'] = "Vous avez payé %s%s d'impôt sur le revenu.",
  
      ['businessTaxPayments_one'] = "Votre entreprise n'a pas pu couvrir le paiement de la taxe d'entreprise de %s%s.",
      ['businessTaxPayments_two'] = "Votre entreprise a payé %s%s d'impôt.",
  
      ['changeTaxCity'] = "Vous avez mis à jour la taxe %s à %s%s.",
  
      ['chargeCityTax'] = "Vous avez payé %s%s de taxe %s.",
  
      ['warnCandidate'] = "Vous avez été averti par le personnel de vote, consultez l'e-mail pour plus d'informations.",
  
      ['removeCandidate'] = "Vous avez retiré %s de la liste des candidats.",
  
      ['sortfunds_one'] = "Vous n'avez pas les fonds nécessaires pour effectuer un retrait.",
      ['sortfunds_two'] = "Vous n'êtes pas autorisé à retirer moins de %s%s.",
      ['sortfunds_three'] = "Vous n'êtes pas autorisé à retirer plus de %s%s.",
      ['sortfunds_four'] = "Vous avez retiré %s%s des fonds de la mairie.",
      ['sortfunds_five'] = "Vous n'avez pas les fonds nécessaires pour effectuer un dépôt.",
      ['sortfunds_six'] = "Vous n'êtes pas autorisé à déposer moins de %s%s.",
      ['sortfunds_seven'] = "Vous n'êtes pas autorisé à déposer plus de %s%s.",
      ['sortfunds_eight'] = "Vous avez déposé %s%s dans les fonds de la mairie.",
  
      ['verifyPin'] = "Un e-mail de code de sécurité a été envoyé à %s.",
  
      ['registerplayercompany'] = "Vous avez enregistré %s dans la base de données de la ville.",
  
      ['transferplayercompany_one'] = "Vous avez transféré la propriété de %s à %s.",
      ['transferplayercompany_two'] = "Cette entreprise appartient au gouvernement et ne peut pas être transférée.",
  
      ['changeplayercompanytax_one'] = "Vous ne pouvez pas fixer le montant de la taxe au-dessus du montant légal !",
      ['changeplayercompanytax_two'] = "Vous ne pouvez pas fixer le montant de la taxe en dessous du montant légal !",
      ['changeplayercompanytax_three'] = "Vous avez modifié la taxe de l'entreprise de %s à %s.",
  
      ['messageOwner'] = "Vous avez reçu un e-mail du bureau du maire.",
  
      ['submitAppointment'] = "Votre demande de rendez-vous a été envoyée.",
  
      ['cancelAppointment'] = "Votre rendez-vous a été annulé.",
  
      ['mayorCancelAppointment'] = "Vous avez annulé le rendez-vous de %s.",
  
      ['issueAppointment'] = "Vous avez programmé un rendez-vous pour %s le %s. Un e-mail a été envoyé avec la date et l'heure.",
  
      ['finishAppointment'] = "Vous avez marqué ce rendez-vous comme terminé.",
  
      ['issueGrant_one'] = "La mairie n'a pas suffisamment de fonds pour couvrir cette subvention.",
      ['issueGrant_two'] = "La mairie ne peut accorder une subvention que de %s%s à %s%s.",
      ['issueGrant_three'] = "La mairie a octroyé une subvention de %s%s à %s.",
      ['issueGrant_four'] = "La mairie a octroyé une subvention de %s%s à %s.",
  
      ['BountySet'] = "Vous avez émis une prime sur %s car son entreprise n'a pas payé les impôts impayés.", 

      ['removedPassedLaw'] = "Vous avez supprimé une loi adoptée : %s, cette loi a été maintenant supprimée de la base de données gouvernementale.",
      ['newLawVoting'] = "Vous avez créé une nouvelle loi : %s, le vote pour celle-ci se terminera dans %s.",
      ['updateVotingDB_one'] = "Votre vote pour %s a été enregistré, vous avez voté en faveur de la loi.",
      ['updateVotingDB_two'] = "Votre vote pour %s a été enregistré, vous avez voté contre la loi.",
      ['calcalateTime'] = "%s jours, %s heures et %s minutes.",
      ['candidateRemove'] = "Vous avez retiré %s du scrutin.",
      ['warnCandidateNew'] = "Vous avez envoyé un avertissement à %s.",  
    }
  }
}
