INSERT INTO `items` (`name`, `label`, `weight`) VALUES
  ('burger', 'Hamburger', 1),
  ('chaser', 'Chaser Choco Bar', 1),
  ('meteorite', 'Meteorite Choco Bar', 1),
  ('hotdog', 'Hotdog', 1),
  ('taco', 'Taco', 1),
  ('piswasser', 'Pißwasser', 1),
  ('mount_whiskey', 'The Mount Whisky', 1),
  ('tequila', 'Tequilya', 1),
  ('nogo_vodka', 'Nogo Vodka', 1),
  ('raine', 'Raine Water', 1),
  ('energy_drink', 'Energy Drink', 1),
  ('alcotester', 'Alcohol Tester', 1),
  ('coffe', 'Coffe', 1),
  ('sprunk', 'Sprunk', 1),
  ('cola', 'Cola', 1),
  ('costa_del_perro', 'Costa Del Perro', 1),
  ('rockford_hill', 'Rockford Hill Reserve', 1),
  ('vinewood_red', 'Vinewood Red Zinfadel', 1),
  ('vinewood_blanc', 'Vinewood Sauvignon Blanc', 1),
  ('bleuterd', 'Bleuterd Champagne', 1),
  ('wine_glass', 'Glass for Wine', 1),
  ('shot_glass', 'Glass for Shots', 1),
  ('whiskey_glass', 'Glass for Whiskey', 1),
  ('flute_glass', 'Glass for Champagne', 1)
;