INSERT INTO `items` (`name`, `label`) VALUES
('bacon_double_cheeseburger', 'Bacon Double Cheeseburger'),
('bacon_ham_sausage', 'Fully Loaded Bacon Ham Sausage'),
('bacon_king', 'Bacon King'),
('big_fish', 'Big Fish'),
('bs_chicken_jr', 'Chicken Jr'),
('bs_hamburger', 'Hamburger'),
('buttermilk_biscuit', 'Fully Loaded Buttermilk'),
('deluxe_chicken_sandwich', 'Ch King Deluxe Chicken Sandwich'),
('bs_mozzarella_sticks', 'Mozzarella Sticks'),
('cheesy_tots', 'Cheesy Tots'),
('chicken_fries', '9 pc Chicken Fries'),
('chicken_nuggets', 'Chicken Nuggets'),
('egg_normous_burrito', 'Egg Normous Burrito'),
('ham_egg_cheese', 'Ham, Egg, & Cheese CroissanWich'),
('jalapeno_cheddar_bites', 'Jalapeno Cheddar Bites'),
('pancake_sausage_platter', 'Pancake & Sausage Platter'),
('bs_coca_cola', 'Medium Coca-Cola'),
('bs_fanta_orange', 'Medium Fanta Orange'),
('bs_fruit_punch', 'Medium Hi-C Fruit Punch'),
('bs_iced_tea', 'Medium Sweetened Iced Tea'),
('bs_sprite', 'Medium Sprite'),
('bs_yello_mello', 'Medium Mello Yello'),
('chocolate_cookie_shake', 'Chocolate OREO Cookie Shake'),
('pink_lemonade', 'Medium Hi-C Pink Lemonade')
;