INSERT INTO `items` (`name`, `label`) VALUES
('buffalo_chicken', 'Buffalo Chicken'),
('cali_chicken_bacon', 'Cali Chicken Bacon'),
('extra_vagan_zza', 'Extra Vagan ZZa'),
('honolulu_hawaiian', 'Honolulu Hawaiian'),
('meat_zza', 'Meat ZZa'),
('memphis_bbq_chicken', 'Memphis BBQ Chicken'),
('pacific_veggie', 'Pacific Veggie'),
('philly_cheese_steak', 'Philly Cheese Steak'),
('pizza_deluxe', 'Pizza Deluxe'),
('spinach_feta', 'Spinach & Feta'),
('ultimate_pepperoni', 'Ultimate Pepperoni'),
('wisconsin_cheese', 'Wisconsin 6 Cheese'),
('chicken_habanero', 'Chicken Habanero'),
('mediterranean_veggie', 'Mediterranean Veggie'),
('philly_cheese_sandwich', 'Philly Cheese Sandwich'),
('chicken_bacon_ranch', 'Chicken Bacon Ranch'),
('italian_sandwich', 'Italian Sandwich'),
('chicken_parm', 'Chicken Parm'),
('p_chicken_alfredo', 'Chicken Alfredo'),
('italian_sausage_marinara', 'Italian Sausage Marinara'),
('chicken_carbonara', 'Chicken Carbonara'),
('pasta_primavera', 'Pasta Primavera'),
('d_coca_cola', 'Coca Cola'),
('d_dr_pepper', 'Dr Pepper'),
('d_fanta_orange', 'Fanta Orange'),
('d_fruit_punch', 'Fruit Punch'),
('d_sprite', 'Sprite')
;