fx_version 'cerulean'
game { 'gta5' }
name 'CarSounds2'
description 'Vehicle Sounds'
author ''
version '1.0'

-- Files
files {
  'audioconfig/*.dat151',
  'audioconfig/*.dat151.nametable',
  'audioconfig/*.dat151.rel',
  'audioconfig/*.dat10.nametable',
  'audioconfig/*.dat10.rel',
  'audioconfig/*.dat10',  
  'audioconfig/*.dat54.nametable',
  'audioconfig/*.dat54.rel',
  'audioconfig/*.dat54',
  'audioconfig/*.dat',
  'sfx/**/*.awc'
}

data_file 'AUDIO_GAMEDATA' 'audioconfig/ta018ferf140b_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta018ferf140b_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta018ferf140b'
data_file 'AUDIO_GAMEDATA' 'audioconfig/harleysound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/harleysound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_harleysound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta007toy2ur_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta007toy2ur_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta007toy2ur'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/nisgtr35_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/nisgtr35_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/nisgtr35_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_nisgtr35'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/918spyeng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/918spyeng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/918spyeng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_918spyeng'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq10nisvr38dett_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq10nisvr38dett_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq10nisvr38dett'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta022s54_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta022s54_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta022s54'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta013vq35_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta013vq35_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta013vq35'
data_file 'AUDIO_GAMEDATA' 'audioconfig/alfa690t_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/alfa690t_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_alfa690t'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/amg1eng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/amg1eng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/amg1eng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_amg1eng'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq03ej257_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq03ej257_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq03ej257'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq05ej257el_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq05ej257el_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq05ej257el'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq11bmw298cc_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq11bmw298cc_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq11bmw298cc'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/camls3v8_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/camls3v8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/camls3v8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_camls3v8'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/chevydmaxeng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/chevydmaxeng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/chevydmaxeng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_chevydmaxeng'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cvpiv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cvpiv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cvpiv8'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/dghmieng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/dghmieng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/dghmieng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_dghmieng'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ecoboostv6_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ecoboostv6_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ecoboostv6'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/frf119eng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/frf119eng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/frf119eng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_frf119eng'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/lamavgineng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lamavgineng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lamavgineng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lamavgineng'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/mbnzc63eng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/mbnzc63eng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mbnzc63eng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mbnzc63eng'
data_file 'AUDIO_GAMEDATA' 'audioconfig/n4g63t_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/n4g63t_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_n4g63t'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/srtvipeng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/srtvipeng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/srtvipeng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_srtvipeng'



-- Audio Game Data
data_file 'AUDIO_GAMEDATA' 'audioconfig/avesv_game.dat'
data_file "AUDIO_GAMEDATA" "audioconfig/kc73pgt3rsakrapovic_game.dat"
data_file 'AUDIO_GAMEDATA' 	'audioconfig/12vcummins_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/46fordmodular_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/53vortec_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/64powerstroke_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/488sound_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/apollosv8_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/argento_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/ariant_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/avesvv12_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/b58b30_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/brabus850_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/c6v8sound_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/c30a_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/cw2019_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/demonv8_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/diablov12_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/dlcenginev10_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/elegyx_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/f136_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/gresleyh_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/gt3flat6_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/gtaspanov10_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/hemisound_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/k20a_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/lambov10_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/lfasound_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/m113k_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/m158huayra_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/m297zonda_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/mclarenv8_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/mercm177_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/mercm279_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/murciev12_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/musv8_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/nfsv8_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/p60b40_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/perfov10_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/porschema2_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/predatorv8_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/r34sound_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/rb26dett_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/roger_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/rotary7_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/s85b50_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/s85b50b_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/sentinelsg4_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/sestov10_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/shonen_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/skart_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/stratumc_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/sultanrsv8_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/toysupmk4_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/urusv8_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/venenov12_game.dat'
data_file 'AUDIO_GAMEDATA' 	'audioconfig/viperv10_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f20c_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/fd3sid_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s54b32_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/z33u2_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/bgw16_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/chevroletlt4_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/13b-rew_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/bmws55_game.dat'

-- Audio Sound Data
data_file 'AUDIO_SOUNDDATA' 'audioconfig/avesv_sounds.dat'
data_file "AUDIO_SOUNDDATA" "audioconfig/kc73pgt3rsakrapovic_sounds.dat"
data_file 'AUDIO_SOUNDDATA' 'audioconfig/12vcummins_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/46fordmodular_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/53vortec_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/64powerstroke_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/488sound_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/apollosv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/argento_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ariant_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/avesvv12_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/b58b30_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/brabus850_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/c6v8sound_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/c30a_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cw2019_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/demonv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/diablov12_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/dlcenginev10_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/elegyx_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f136_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/gresleyh_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/gt3flat6_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/gtaspanov10_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/hemisound_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/k20a_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lambov10_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lfasound_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/m113k_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/m158huayra_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/m297zonda_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mclarenv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mercm177_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mercm279_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/murciev12_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/musv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/nfsv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/p60b40_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/perfov10_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/porschema2_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/predatorv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/r34sound_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/rb26dett_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/roger_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/rotary7_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s85b50_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s85b50b_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sentinelsg4_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sestov10_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/shonen_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/skart_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/stratumc_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sultanrsv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/toysupmk4_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/urusv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/venenov12_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/viperv10_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f20c_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/fd3sid_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s54b32_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/z33u2_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/bgw16_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/chevroletlt4_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/13b-rew_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/bmws55_sounds.dat'

-- Audio Synthersizer Data
data_file 'AUDIO_SYNTHDATA' 'audioconfig/c30a_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/f136_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/gresleyh_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/gt3flat6_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/k20a_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/m158huayra_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/m297zonda_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/rb26dett_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/shonen_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/stratumc_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/fd3sid_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/z33u2_amp.dat'
data_file "AUDIO_SYNTHDATA" "audioconfig/kc73pgt3rsakrapovic_amp.dat"
data_file 'AUDIO_SYNTHDATA' 'audioconfig/bgw16_amp.dat'

-- Audio Wavepacks
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_avesv'
data_file "AUDIO_WAVEPACK" "sfx/dlc_kc73pgt3rsakrapovic"
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_12vcummins'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_46fordmodular'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_53vortec'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_64powerstroke'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_488sound'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_apollosv8'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_argento'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ariant'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_avesvv12'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_b58b30'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_brabus850'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_c6v8sound'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_c30a'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cw2019'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_demonv8'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_diablov12'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_elegyx'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_enginev10'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f136'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_gresleyh'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_gt3flat6'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_gtaspanov10'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_hemisound'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_k20a'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lambov10'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lfasound'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_m113k'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_m158huayra'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_m297zonda'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mclarenv8'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mercm177'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mercm279'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_murciev12'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_musv8'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_nfsv8'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_p60b40'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_perfov10'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_porschema2'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_predatorv8'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_r34sound'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rb26dett'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_roger'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rotary7'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s85b50'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s85b50b'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_sentinelsg4'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_sestov10'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_shonen'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_skart'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_toysupmk4'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_urusv8'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_venenov12'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_viperv10'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f20c'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_fd3sid'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s54b32'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_z33u2'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_bgw16'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_chevroletlt4'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_13b-rew'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_bmws55'
data_file 'AUDIO_WAVEPACK' 'sfx/resident'



-------------old

data_file 'AUDIO_GAMEDATA' 'audioconfig/aq2jzgterace_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq2jzgterace_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq2jzgterace'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aqls7raceswap_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aqls7raceswap_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aqls7raceswap'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aqm275amg_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aqm275amg_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aqm275amg'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aqtoy2jzstock_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aqtoy2jzstock_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aqtoy2jzstock'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aston59v12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aston59v12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aston59v12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/audiwx_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/audiwx_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_audiwx'
data_file 'AUDIO_GAMEDATA' 'audioconfig/audi7a_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/audi7a_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_audi7a'
data_file 'AUDIO_GAMEDATA' 'audioconfig/audiea855_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/audiea855_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_audiea855'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/audr8tteng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/audr8tteng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/audr8tteng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_audr8tteng'
data_file 'AUDIO_GAMEDATA' 'audioconfig/n55b30t0_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/n55b30t0_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_n55b30t0'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s55b30_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s55b30_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s55b30'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cammedcharger_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cammedcharger_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cammedcharger'
data_file 'AUDIO_GAMEDATA' 'audioconfig/chevroletlt4_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/chevroletlt4_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_chevroletlt4'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cummins5924v_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cummins5924v_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cummins5924v'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ea825_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ea825_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ea825'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ea888_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ea888_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ea888'
data_file 'AUDIO_GAMEDATA' 'audioconfig/fordvoodoo_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/fordvoodoo_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_fordvoodoo'
data_file 'AUDIO_GAMEDATA' 'audioconfig/gallardov10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/gallardov10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_gallardov10'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/gt3rstun_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/gt3rstun_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/gt3rstun_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_gt3rstun'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/lgcy01chargerv8_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lgcy01chargerv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lgcy01chargerv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lgcy01chargerv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/m5cracklemod_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/m5cracklemod_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_m5cracklemod'
data_file 'AUDIO_GAMEDATA' 'audioconfig/mercedesm113_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mercedesm113_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mercedesm113'
data_file 'AUDIO_GAMEDATA' 'audioconfig/mercedesm155_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mercedesm155_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mercedesm155'
data_file 'AUDIO_GAMEDATA' 'audioconfig/npolchar_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/npolchar_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_npolchar'
data_file 'AUDIO_GAMEDATA' 'audioconfig/porsche57v10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/porsche57v10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_porsche57v10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s63b44_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s63b44_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s63b44'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s65b40_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s65b40_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s65b40'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta4b11_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta4b11_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta4b11'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta006bmws65_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta006bmws65_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta006bmws65'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta011mit4g63_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta011mit4g63_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta011mit4g63'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta028viper_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta028viper_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta028viper'
data_file 'AUDIO_GAMEDATA' 'audioconfig/taaud40v8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/taaud40v8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_taaud40v8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tacumminsb_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tacumminsb_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tacumminsb'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tagt3flat6_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tagt3flat6_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tagt3flat6'
data_file 'AUDIO_GAMEDATA' 'audioconfig/talam52v10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/talam52v10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_talam52v10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tamustanggt50_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tamustanggt50_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tamustanggt50'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tascmustanggt50_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tascmustanggt50_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tascmustanggt50'
data_file 'AUDIO_GAMEDATA' 'audioconfig/v6audiea839_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/v6audiea839_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_v6audiea839'
data_file 'AUDIO_GAMEDATA' 'audioconfig/r35sound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/r35sound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_r35sound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/veyronsound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/veyronsound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_veyronsound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/suzukigsxr1k_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/suzukigsxr1k_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_suzukigsxr1k'
data_file "AUDIO_SYNTHDATA" "audioconfig/bmws1krreng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/bmws1krreng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/bmws1krreng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_bmws1krreng"
data_file "AUDIO_GAMEDATA" "audioconfig/kc74s1000rrakevoline_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/kc74s1000rrakevoline_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_kc74s1000rrakevoline"























