-- copy these items after the last item in your ox-inventory/data/items.lua

["chain_medal"] = {
    label = "Chain Medal",
    weight = 1,
    stack = true,
    close = true,
},
["chain_ls"] = {
    label = "Chain LS",
    weight = 1,
    stack = true,
    close = true,
},
["chain_is"] = {
    label = "Chain IS",
    weight = 1,
    stack = true,
    close = true,
},
["chain_triangle"] = {
    label = "Chain Triangle",
    weight = 1,
    stack = true,
    close = true,
},
["chain_dogtag"] = {
    label = "Chain Dogtag",
    weight = 1,
    stack = true,
    close = true,
},
["chain_richman"] = {
    label = "Chain Richman",
    weight = 1,
    stack = true,
    close = true,
},
["chain_m"] = {
    label = "Chain M",
    weight = 1,
    stack = true,
    close = true,
},
["casino_earrings"] = {
    label = "Casino Earrings",
    weight = 1,
    stack = true,
    close = true,
},
["diagold_earrings"] = {
    label = "Diagold Earrings",
    weight = 1,
    stack = true,
    close = true,
},
["diaplatinum_earrings"] = {
    label = "Diaplatinum Earrings",
    weight = 1,
    stack = true,
    close = true,
},
["earrings_sgold"] = {
    label = "Earrings SGold",
    weight = 1,
    stack = true,
    close = true,
},
["goldak_earrings"] = {
    label = "GoldAK Earrings",
    weight = 1,
    stack = true,
    close = true,
},
["goldhex_earrings"] = {
    label = "GoldHex Earrings",
    weight = 1,
    stack = true,
    close = true,
},
["goldstone_earrings"] = {
    label = "Goldstone Earrings",
    weight = 1,
    stack = true,
    close = true,
},
["hex4you_earrings"] = {
    label = "Hex4You Earrings",
    weight = 1,
    stack = true,
    close = true,
},
["hexdia_earrings"] = {
    label = "HexDia Earrings",
    weight = 1,
    stack = true,
    close = true,
},
["karaoke_earrings"] = {
    label = "Karaoke Earrings",
    weight = 1,
    stack = true,
    close = true,
},
["platbox_earrings"] = {
    label = "Platbox Earrings",
    weight = 1,
    stack = true,
    close = true,
},
["rectdia_earrings"] = {
    label = "RectDia Earrings",
    weight = 1,
    stack = true,
    close = true,
},
["skull_earrings"] = {
    label = "Skull Earrings",
    weight = 1,
    stack = true,
    close = true,
},
["skull_bracelet"] = {
    label = "Skull Bracelet",
    weight = 1,
    stack = true,
    close = true,
},
["necklace_family"] = {
    label = "Necklace Family",
    weight = 1,
    stack = true,
    close = true,
},
["necklace_dogtag"] = {
    label = "Necklace Dogtag",
    weight = 1,
    stack = true,
    close = true,
},
["covgari_gold"] = {
    label = "Covgari Gold",
    weight = 1,
    stack = true,
    close = true,
},
["crowex_black"] = {
    label = "Crowex Black",
    weight = 1,
    stack = true,
    close = true,
},
["crowex_brown"] = {
    label = "Crowex Brown",
    weight = 1,
    stack = true,
    close = true,
},
["hex_gold"] = {
    label = "Hex Gold",
    weight = 1,
    stack = true,
    close = true,
},
["kronos_black"] = {
    label = "Kronos Black",
    weight = 1,
    stack = true,
    close = true,
},
["kronos_gold"] = {
    label = "Kronos Gold",
    weight = 1,
    stack = true,
    close = true,
},
["pendulus_platinum"] = {
    label = "Pendulus Platinum",
    weight = 1,
    stack = true,
    close = true,
},
["diamond"] = {
    label = "Diamond",
    weight = 1,
    stack = true,
    close = true,
},
["gold_bar"] = {
    label = "Gold Bar",
    weight = 1,
    stack = true,
    close = true,
},
["platinum_bar"] = {
    label = "Platinum Bar",
    weight = 1,
    stack = true,
    close = true,
},
["watch_material"] = {
    label = "Watch Material",
    weight = 1,
    stack = true,
    close = true,
},
["blue_stone"] = {
    label = "Blue Stone",
    weight = 1,
    stack = true,
    close = true,
},
["green_stone"] = {
    label = "Green Stone",
    weight = 1,
    stack = true,
    close = true,
},
["red_stone"] = {
    label = "Red Stone",
    weight = 1,
    stack = true,
    close = true,
},
["white_stone"] = {
    label = "White Stone",
    weight = 1,
    stack = true,
    close = true,
},
["pearl"] = {
    label = "Pearl",
    weight = 1,
    stack = true,
    close = true,
},
["fs_chain"] = {
    label = "Chain",
    weight = 1,
    stack = true,
    close = true,
},
["black_stone"] = {
    label = "Black Stone",
    weight = 1,
    stack = true,
    close = true,
},
["earring_material"] = {
    label = "Earring Base",
    weight = 1,
    stack = true,
    close = true,
},