    -- add the items below to qs-inventory/shared/items.lua
    -- Ingredients

    ["bahama_mug"] 				= {["name"] = "bahama_mug", 		["label"] = "Empty Mug",		["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_mug.png", 		 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_glass"] 			= {["name"] = "bahama_glass", 		["label"] = "Empty Glass", 		["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_glass.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_shotglass"] 		= {["name"] = "bahama_shotglass",	["label"] = "Empty Shot Glass",	["weight"] = 100,		["type"] = "item",		["image"] = "bahama_shotglass.png",	 ["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,   ["combinable"] = nil,   ["description"] = "An Ingredient" },
    ["bahama_whiskey"] 		 	= {["name"] = "bahama_whiskey", 	["label"] = "Whiskey", 			["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_whiskey.png",    ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_tequila"] 	    	= {["name"] = "bahama_tequila", 	["label"] = "Tequila",     		["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_tequila.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_vodka"] 			= {["name"] = "bahama_vodka", 	    ["label"] = "Vodka", 			["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_vodka.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_rum"] 	        	= {["name"] = "bahama_rum", 		["label"] = "Rum",     		    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_rum.png", 	     ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_gin"] 				= {["name"] = "bahama_gin", 	    ["label"] = "Gin",			    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_gin.png", 		 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_cachaca"]    		= {["name"] = "bahama_cachaca", 	["label"] = "Cachaça",        	["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_cachaca.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_curacao"] 			= {["name"] = "bahama_curacao", 	["label"] = "Blue Curacao", 	["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_curacao.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_champagne"] 		= {["name"] = "bahama_champagne", 	["label"] = "Champagne", 	    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_champagne.png",  ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_strawberry"] 	    = {["name"] = "bahama_strawberry",  ["label"] = "Strawberry",       ["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_strawberry.png", ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_lime"] 	        = {["name"] = "bahama_lime",        ["label"] = "Lime",             ["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_lime.png", 	     ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_pineapple"] 		= {["name"] = "bahama_pineapple", 	["label"] = "Pineapple",     	["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_pineapple.png",  ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_cranjuice"] 		= {["name"] = "bahama_cranjuice", 	["label"] = "Cranberry Juice",	["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_cranjuice.png",  ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_ojuice"] 			= {["name"] = "bahama_ojuice", 		["label"] = "Orange Juice", 	["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_ojuice.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_coffee"] 			= {["name"] = "bahama_coffee",		["label"] = "Coffee",			["weight"] = 100,		["type"] = "item",		["image"] = "bahama_coffee.png",	 ["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,   ["combinable"] = nil,   ["description"] = "An Ingredient" },
    ["bahama_sugarcube"] 		= {["name"] = "bahama_sugarcube", 	["label"] = "Sugar Cubes", 		["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_sugarcube.png",  ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_icecube"] 	    	= {["name"] = "bahama_icecube", 	["label"] = "Ice Cubes",     	["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_icecube.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_jello"] 			= {["name"] = "bahama_jello", 	    ["label"] = "Jello Mix", 		["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_jello.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},

    ["bm_oldfashion"] 			= {["name"] = "bm_oldfashion", 		["label"] = "Old Fashioned",	["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_oldfashion.png", 	 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Old Fashioned!"},
    ["bm_pinacolada"] 			= {["name"] = "bm_pinacolada", 		["label"] = "Pina Colada",	    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_pinacolada.png", 	 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Pina Colada!"},
    ["bm_cosmopolitan"] 		= {["name"] = "bm_cosmopolitan", 	["label"] = "Cosmopolitan",	    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_cosmopolitan.png", 	 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Cosmopolitan!"},
    ["bm_daiquiri"] 			= {["name"] = "bm_daiquiri", 		["label"] = "Daiquiri",	        ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_daiquiri.png", 		 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Daiquiri!"},
    ["bm_martini"] 			    = {["name"] = "bm_martini", 		["label"] = "Martini",	        ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_martini.png", 		 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Martini!"},
    ["bm_kahlua"] 			    = {["name"] = "bm_kahlua", 		    ["label"] = "Kahlua",	        ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_kahlua.png", 		 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Kahlua Cocktail!"},
    ["bm_mimosa"] 			    = {["name"] = "bm_mimosa", 		    ["label"] = "Mimosa",	        ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_mimosa.png", 		 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Mimosa Cocktail!"},
    ["bm_whiskeysour"] 			= {["name"] = "bm_whiskeysour", 	["label"] = "Whiskey Sour",	    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_whiskeysour.png", 	 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Whiskey Sour!"},
    ["bm_bluelagoon"] 			= {["name"] = "bm_bluelagoon", 		["label"] = "Blue Lagoon",	    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_bluelagoon.png", 	 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Blue Lagoon Cocktail!"},

    ["bm_tequilashot"] 			= {["name"] = "bm_tequilashot", 	["label"] = "Tequila Shot",	    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_tequilashot.png", 	 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Tequila Shot!"},
    ["bm_whiskeyshot"] 			= {["name"] = "bm_whiskeyshot", 	["label"] = "Whiskey Shot",	    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_whiskeyshot.png", 	 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Whiskey Shot!"},
    ["bm_seabreezeshot"] 		= {["name"] = "bm_seabreezeshot", 	["label"] = "SeaBreeze Shot",	["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_seabreezeshot.png",  ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Sea Breeze Shot!"},
    ["bm_caipirinhashot"] 		= {["name"] = "bm_caipirinhashot", 	["label"] = "Caipirinha Shot",	["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_caipirinhashot.png", ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Caipirinha Shot!"},
    ["bm_jelloshot"] 			= {["name"] = "bm_jelloshot", 		["label"] = "Jello Shot",	    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_jelloshot.png", 	 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Jello Shot!"},

    ["bm_budlite"] 			    = {["name"] = "bm_budlite", 		["label"] = "Budlite Beer",	    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_budlite.png", 		 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Draft Bud Lite!"},
    ["bm_millerlite"] 			= {["name"] = "bm_millerlite", 		["label"] = "Millerlite Beer",	["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_millerlite.png", 	 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Draft Miller Lite!"},
    ["bm_coorslite"] 			= {["name"] = "bm_coorslite", 		["label"] = "Coorslite Beer",	["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_coorslite.png", 	 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Draft Coors Lite!"},
    ["bm_corona"] 			    = {["name"] = "bm_corona", 		    ["label"] = "Corona Beer",	    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_corona.png", 		 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Draft Corona!"},

    -- Ingredients
    ["bahama_ccheese"] 			= {["name"] = "bahama_ccheese", 	["label"] = "Cream Cheese", 	["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_ccheese.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_mango"] 			= {["name"] = "bahama_mango", 	    ["label"] = "Mango", 		    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_mango.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_cheddar"] 			= {["name"] = "bahama_cheddar", 	["label"] = "Cheddar", 		    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_cheddar.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_rawwing"] 			= {["name"] = "bahama_rawwing", 	["label"] = "Raw Wings", 		["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_rawwing.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_seasoning"] 		= {["name"] = "bahama_seasoning", 	["label"] = "Seasonings", 		["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_seasoning.png",  ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_chips"] 			= {["name"] = "bahama_chips", 	    ["label"] = "Tortilla Chips", 	["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_chips.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_beef"] 			= {["name"] = "bahama_beef", 	    ["label"] = "Beef", 		    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_beef.png", 	     ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_avocado"] 			= {["name"] = "bahama_avocado", 	["label"] = "Avocado", 		    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_avocado.png", 	     ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_peppers"] 			= {["name"] = "bahama_peppers", 	["label"] = "Peppers", 		    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_peppers.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_bbq"] 			    = {["name"] = "bahama_bbq", 	    ["label"] = "BBQ Sauce", 		["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_bbq.png", 	     ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_shrimp"] 			= {["name"] = "bahama_shrimp", 	    ["label"] = "Raw Shrimp", 		["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_shrimp.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_rawchik"] 			= {["name"] = "bahama_rawchik", 	["label"] = "Raw Chicken", 		["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_rawchik.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_eggs"] 			= {["name"] = "bahama_eggs", 	    ["label"] = "Fresh Eggs", 		["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_eggs.png", 	     ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_bredcrum"] 		= {["name"] = "bahama_bredcrum", 	["label"] = "Breadcrumbs", 		["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_bredcrum.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},
    ["bahama_butter"] 			= {["name"] = "bahama_butter", 	    ["label"] = "Butter", 		    ["weight"] = 100, 		["type"] = "item", 		["image"] = "bahama_butter.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "An Ingredient"},

    -- Water is already a default QBCore item but just in-case it isn't, uncomment this.
    ["water_bottle"] 			= {["name"] = "water_bottle", 	    ["label"] = "Water", 		    ["weight"] = 100, 		["type"] = "item", 		["image"] = "water_bottle.png", 	 ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Quality H20"},

    --- Foods
    ["bm_wings"] 			    = {["name"] = "bm_wings", 		    ["label"] = "Jerk Chicken Wings", ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_wings.png", 		 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Jerk Chicken Wings!"},
    ["bm_rissole"] 			    = {["name"] = "bm_rissole", 		["label"] = "Chicken Rissole",	  ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_rissole.png", 		 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Chicken Ball Rissole!"},
    ["bm_mgocake"] 			    = {["name"] = "bm_mgocake", 		["label"] = "Mango Cheesecake",	  ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_mgocake.png", 		 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Mango Cream Cheesecake!"},
    ["bm_caridea"] 			    = {["name"] = "bm_caridea", 		["label"] = "Shrimp Caridean",	  ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_caridea.png", 		 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Shrimp Squid Caridean!"},
    ["bm_kebab"] 			    = {["name"] = "bm_kebab", 		    ["label"] = "BBQ Beef Kebab",	  ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_kebab.png", 		 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama BBQ Beef Kebab!"},
    ["bm_nachos"] 			    = {["name"] = "bm_nachos", 		    ["label"] = "Guac Nachos",	      ["weight"] = 100, 		["type"] = "item", 		["image"] = "bm_nachos.png", 		 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Bahama Mama Beef and Guacamole Nachos!"},


