INSERT INTO `items` (`name`, `label`) VALUES
('beefy_nacho', 'Beefy Nacho'),
('chalupa_supreme', 'Chalupa Supreme'),
('cheese_quesadilla', 'Cheese Quesadilla'),
('cheesy_black_bean', 'Cheesy Black Bean'),
('cheesy_gordita_crunch', 'Cheesy Gordita Crunch'),
('chicken_burrito', 'Chicken Burrito'),
('churros_dip', 'Churros Dip'),
('cinnamon_twists', 'Cinnamon Twists'),
('crispy_chicken_staco', 'Crispy Chicken Soft Taco'),
('crunchwrap_supreme', 'Crunchwrap Supreme'),
('crunchy_taco_supreme', 'Crunchy Taco Supreme'),
('crunchy_taco_supreme', 'Crunchy Taco Supreme'),
('crunchytaco', 'Crunchy Taco'),
('fishtaco', 'Fish Taco'),
('fries_grande', 'Fries Grande'),
('quesadilla', 'Quesadilla'),
('soft_taco', 'Soft Taco'),
('soft_taco_supreme', 'Soft Taco Supreme'),
('spicy_chicken_burrito', 'Spicy Chicken Burrito'),
('taco_regular', 'Taco Regular'),
('tacomeet', 'Taco Meet'),
('volcano_burrito', 'Volcano Burrito'),
('t_diet_pepsi', 'Diet Pepsi'),
('t_seven_up', 'Seven Up'),
('t_tango_apple', 'Tango Apple'),
('t_tango_orange', 'Tango Orange')
;