INSERT INTO `items` (`name`, `label`) VALUES
('gelatti_joint', 'Gelatti Joint'),
('gary_payton_joint', 'Gary Payton Joint'),
('cereal_milk_joint', 'Cereal Milk Joint'),
('cheetah_piss_joint', 'Cheetah Piss Joint'),
('snow_man_joint', 'Snow Man Joint'),
('georgia_pie_joint', 'Georgia Pie Joint'),
('jefe_joint', 'Jefe Joint'),
('cake_mix_joint', 'Cake Mix Joint'),
('white_runtz_joint', 'White Runtz Joint'),
('blueberry_cruffin_joint', 'Blueberry Cruffin Joint'),
('whitecherry_gelato_joint', 'Whitecherry Gelato Joint'),
('fine_china_joint', 'Fine China Joint'),
('pink_sandy_joint', 'Pink Sandy Joint'),
('zushi_joint', 'Zushi Joint'),
('apple_gelato_joint', 'Apple Gelato Joint'),
('biscotti_joint', 'Biscotti Joint'),
('collins_ave_joint', 'Collins AVE Joint'),
('marathon_joint', 'Marathon Joint'),
('oreoz_joint', 'Oreoz Joint'),
('pirckly_pear_joint', 'Pirckly Pear Joint'),
('runtz_og_joint', 'Runtz OG Joint'),
('blue_tomyz_joint', 'Blue Tomyz Joint'),
('ether_joint', 'Ether Joint'),
('froties_joint', 'Froties Joint'),
('gmo_cookies_joint', 'GMO cookies Joint'),
('ice_cream_cake_pack_joint', 'Ice Cream Cake Pack Joint'),
('khalifa_kush_joint', 'Khalifa Kush Joint'),
('la_confidential_joint', 'LA Confidential Joint'),
('marshmallow_og_joint', 'Marshmallow OG Joint'),
('moon_rock_joint', 'Moon Rock Joint'),
('sour_diesel_joint', 'Sour Diesel Joint'),
('tahoe_og_joint', 'Tahoe OG Joint'),

('gelatti', 'Gelatti'),
('gary_payton', 'Gary Payton'),
('cereal_milk', 'Cereal Milk'),
('cheetah_piss', 'Cheetah Piss'),
('snow_man', 'Snow Man'),
('georgia_pie', 'Georgia Pie'),
('jefe', 'Jefe'),
('cake_mix', 'Cake Mix'),
('white_runtz', 'White Runtz'),
('whitecherry_gelato', 'Whitecherry Gelato'),
('blueberry_cruffin', 'Blueberry Cruffin'),
('fine_china', 'Fine China'),
('pink_sandy', 'Pink Sandy'),
('zushi', 'Zushi'),
('apple_gelato', 'Apple Gelato'),
('biscotti', 'Biscotti'),
('collins_ave', 'Collins AVE'),
('marathon', 'Marathon'),
('oreoz', 'Oreoz'),
('pirckly_pear', 'Pirckly Pear'),
('runtz_og', 'Runtz OG'),
('blue_tomyz', 'Blue Tomyz'),
('ether', 'Ether'),
('froties', 'Froties'),
('gmo_cookies', 'GMO cookies'),
('ice_cream_cake_pack', 'Ice Cream Cake Pack'),
('khalifa_kush', 'Khalifa Kush'),
('la_confidential', 'LA Confidential'),
('marshmallow_og', 'Marshmallow OG'),
('moon_rock', 'Moon Rock'),
('sour_diesel', 'Sour Diesel'),
('tahoe_og', 'Tahoe OG'),

('blueberry_jam_cookie', 'Blueberry Jam Cookie'),
('butter_cookie', 'Butter Cookie'),
('cookie_craze', 'Cookie Craze'),
('get_figgy', 'Get Figgy'),
('key_lime_cookie', 'Key Lime Cookie'),
('marshmallow_crisp', 'Marshmallow Crisp'),
('no_99', 'NO 99'),
('paris_fog', 'Paris Fog'),
('pogo', 'Pogo'),
('pumpkin_cookie', 'Pumpkin Cookie'),
('shamrock_cookie', 'Shamrock Cookie'),
('strawberry_jam_cookie', 'Strawberry Jam Cookie'),

('lighter', 'Lighter'),
('empty_vape', 'Empty Vape'),
('empty_joint_pack', 'Empty Joint Pack'),
('cutter', 'Cutter')
;