INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`)
VALUES 
('lcmarshmellow', 'Marshmellows', 5, 0, 1),
('lcchocolate', 'Chocolate Bar', 5, 0, 1),
('lcgramcrkrs', 'Graham Crackers', 5, 0, 1),
('lccampmeat', 'Raw Beef', 5, 0, 1),
('lccampherbs', 'Wild Herbs', 5, 0, 1),
('lccampbeans', 'Canned beans', 5, 0, 1),
('lccampcorn', 'Ear Corn', 5, 0, 1),
('lccamppotato', 'Potato', 5, 0, 1),
('lccampbutta', 'Butter', 5, 0, 1),
('lccampfish', 'Fresh Fish', 5, 0, 1),
('lcsmores', 'Smores', 5, 0, 1),
('lccookedsteak', 'Grilled Steak', 5, 0, 1),
('lccookedbeans', 'Warmed Beans', 5, 0, 1),
('lccookedcorn', 'Cooked Corn', 5, 0, 1),
('lccookedfish', 'Cooked Fish', 5, 0, 1),
('lccookedpotato', 'Cooked Potato', 5, 0, 1),
('lcherbtea', 'Herbal Tea', 5, 0, 1),
('lcwater', 'Water', 5, 0, 1),
('lccampcoffee', 'Coffee', 5, 0, 1),
('lc_camptent', 'Camp Tent', 5, 0, 1),
('lc_campchair', 'Camp Chair', 5, 0, 1),
('lc_campbed', 'Camp Bed', 5, 0, 1),
('lc_campcooler', 'Camp Cooler', 5, 0, 1),
('lc_campgrill', 'Camp Grill', 5, 0, 1),
('lc_campwood', 'Camp Firewood', 5, 0, 1);