DELETE FROM items WHERE name = 'WEAPON_GLOCK19X';
DELETE FROM items WHERE name = 'WEAPON_GLOCK19';
DELETE FROM items WHERE name = 'WEAPON_GLOCK40';
DELETE FROM items WHERE name = 'WEAPON_GLOCK40S';
DELETE FROM items WHERE name = 'WEAPON_DDM4V5';
DELETE FROM items WHERE name = 'WEAPON_MPX';
DELETE FROM items WHERE name = 'WEAPON_PD509';
DELETE FROM items WHERE name = 'WEAPON_APS';
DELETE FROM items WHERE name = 'WEAPON_PPK';
DELETE FROM items WHERE name = 'WEAPON_PITVIPER';
DELETE FROM items WHERE name = 'WEAPON_BARP';
DELETE FROM items WHERE name = 'WEAPON_RDP';
DELETE FROM items WHERE name = 'WEAPON_LOK';
DELETE FROM items WHERE name = 'WEAPON_PLR';
DELETE FROM items WHERE name = 'WEAPON_XDS9';
DELETE FROM items WHERE name = 'WEAPON_PPS';
DELETE FROM items WHERE name = 'WEAPON_XDME';
DELETE FROM items WHERE name = 'WEAPON_SP';
DELETE FROM items WHERE name = 'WEAPON_GLOCK17S';
DELETE FROM items WHERE name = 'WEAPON_GLOCK18C';
DELETE FROM items WHERE name = 'WEAPON_GLOCK19S';
DELETE FROM items WHERE name = 'WEAPON_ARPISTOL';
DELETE FROM items WHERE name = 'WEAPON_GLOCK26S';
DELETE FROM items WHERE name = 'WEAPON_GRENADES';
DELETE FROM items WHERE name = 'WEAPON_M32S';
DELETE FROM items WHERE name = 'WEAPON_MICRODRACO';
DELETE FROM items WHERE name = 'WEAPON_RUGER57';
DELETE FROM items WHERE name = 'WEAPON_MK18';
DELETE FROM items WHERE name = 'WEAPON_680';
DELETE FROM items WHERE name = 'WEAPON_ZIPTIE';

DELETE FROM items WHERE name = 'COMPONENT_ZIPTIE_BOXMAG';
DELETE FROM items WHERE name = 'COMPONENT_ARPISTOL_BOXMAG';
DELETE FROM items WHERE name = 'COMPONENT_PLR_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_BARP_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_GLOCK18C_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_GLOCK17_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_AT_AR_LOKAFGRIP';
DELETE FROM items WHERE name = 'COMPONENT_AT_AR_BARPFLSH';
DELETE FROM items WHERE name = 'COMPONENT_AT_PI_RUGER57FLSH';
DELETE FROM items WHERE name = 'COMPONENT_GLOCK19X_CLIP_03';
DELETE FROM items WHERE name = 'COMPONENT_GLOCK19_CLIP_03';
DELETE FROM items WHERE name = 'COMPONENT_GLOCK40S_CLIP_03';
DELETE FROM items WHERE name = 'COMPONENT_GLOCK40_CLIP_03';
DELETE FROM items WHERE name = 'COMPONENT_GLOCK18C_CLIP_03';
DELETE FROM items WHERE name = 'COMPONENT_GLOCK19X_CLIP_04';
DELETE FROM items WHERE name = 'COMPONENT_GLOCK40_CLIP_04';
DELETE FROM items WHERE name = 'COMPONENT_GLOCK40S_CLIP_04';
DELETE FROM items WHERE name = 'COMPONENT_APS_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_XDS9_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_AT_AR_ZIPTIE_SUPP';
DELETE FROM items WHERE name = 'COMPONENT_GLOCK19_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_GLOCK40_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_GLOCK19X_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_GLOCK40S_CLIP_02';

INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
('WEAPON_GLOCK19X', 'G19X XL', 1, 0, 1),
('WEAPON_GLOCK19', 'GLOCK 19', 2, 0, 1),
('WEAPON_GLOCK40', 'GLOCK 40', 2, 0, 1),
('WEAPON_GLOCK40S', 'GLOCK 40 SWITCH', 1, 0, 1),
('WEAPON_DDM4V5', 'DDM4V5', 2, 0, 1),
('WEAPON_MPX', 'MPX', 3, 0, 1),
('WEAPON_PD509', 'PD 509', 2, 0, 1),
('WEAPON_APS', 'STECHKIN APS', 1, 0, 1),
('WEAPON_PPK', 'WALTHER PPK', 1, 0, 1),
('WEAPON_PITVIPER', 'JW4 PIT VIPER', 1, 0, 1),
('WEAPON_BARP', 'BANSHEE ARP-9', 1, 0, 1),
('WEAPON_RDP', 'HELLCAT RDP', 1, 0, 1),
('WEAPON_LOK', 'M-LOK AR 15', 1, 0, 1),
('WEAPON_PLR', 'PLR-16', 1, 0, 1),
('WEAPON_XDS9', 'XDS9', 1, 0, 1),
('WEAPON_PPS', 'WALTHER PPS', 1, 0, 1),
('WEAPON_XDME', 'XDM ELITE', 1, 0, 1),
('WEAPON_SP', 'FN-15 PISTOL', 2, 0, 1),
('WEAPON_GLOCK17S', 'GLOCK 17 SWITCH', 2, 0, 1),
('WEAPON_GLOCK18C', 'GLOCK 18C', 1, 0, 1),
('WEAPON_GLOCK19S', 'GLOCK 19 SWITCH', 3, 0, 1),
('WEAPON_ARPISTOL', 'TATIC ARP 9MM', 3, 0, 1),
('WEAPON_GLOCK26S', 'GLOCK 26 SWITCH', 2, 0, 1),
('WEAPON_GRENADES', 'GRENADE SNIPER', 1, 0, 1),
('WEAPON_M32S', 'M32 SMOKE GL', 1, 0, 1),
('WEAPON_MICRODRACO', 'MICRO DRACO', 1, 0, 1),
('WEAPON_RUGER57', 'RUGER 57', 1, 0, 1),
('WEAPON_MK18', 'MK18 MOD 1', 1, 0, 1),
('WEAPON_680', 'MODEL 680', 1, 0, 1),
('WEAPON_ZIPTIE', 'ZIP TIE M4A1', 1, 0, 1),

('COMPONENT_ZIPTIE_BOXMAG', 'Extended ZIPTIE Clip', 1, 0, 1),
('COMPONENT_ARPISTOL_BOXMAG', 'Extended ARP Clip', 1, 0, 1),
('COMPONENT_PLR_CLIP_02', 'Extended PLR-16 Clip', 1, 0, 1),
('COMPONENT_XDS9_CLIP_02', 'Extended XDS9 Clip', 1, 0, 1),
('COMPONENT_APS_CLIP_02', 'Extended APS Clip', 1, 0, 1),

('COMPONENT_BARP_CLIP_02', 'Extended B-ARP Clip', 1, 0, 1),

('COMPONENT_GLOCK19_CLIP_02', 'Extended G19 Clip', 1, 0, 1),
('COMPONENT_GLOCK40_CLIP_02', 'Extended G40 Clip', 1, 0, 1),
('COMPONENT_GLOCK19X_CLIP_02', 'Extended G19X Clip', 1, 0, 1),
('COMPONENT_GLOCK40S_CLIP_02', 'Extended G40S Clip', 1, 0, 1),

('COMPONENT_GLOCK18C_CLIP_02', 'Extended G18C Clip', 1, 0, 1),
('COMPONENT_GLOCK17_CLIP_02', 'Extended G17 Clip', 1, 0, 1),
('COMPONENT_AT_AR_LOKAFGRIP', 'Extended LOK Clip', 1, 0, 1),

('COMPONENT_AT_AR_BARPFLSH', 'Extended B-ARP Flashlight', 1, 0, 1),
('COMPONENT_AT_PI_RUGER57FLSH', 'Extended Ruger Flashlight', 1, 0, 1),

('COMPONENT_GLOCK19X_CLIP_03', 'G19X Drum Mag', 1, 0, 1),
('COMPONENT_GLOCK19_CLIP_03', 'G19 Drum Mag', 1, 0, 1),
('COMPONENT_GLOCK40S_CLIP_03', 'G40S Drum Mag', 1, 0, 1),
('COMPONENT_GLOCK40_CLIP_03', 'G40 Drum Mag', 1, 0, 1),
('COMPONENT_GLOCK18C_CLIP_03', 'G18C Drum Mag', 1, 0, 1),

('COMPONENT_GLOCK19X_CLIP_04', 'G19X 100 Round Mag', 1, 0, 1),
('COMPONENT_GLOCK40_CLIP_04', 'G40 100 Round Mag', 1, 0, 1),
('COMPONENT_GLOCK40S_CLIP_04', 'G40S 100 Round Mag', 1, 0, 1);

('COMPONENT_AT_AR_ZIPTIE_SUPP', 'ZIPTIE Suppressor', 1, 0, 1);