INSERT INTO `items` (`name`, `label`) VALUES
('brown_scramble_bowl', 'Brown Scramble Bowl'),
('brown_scramble_burrito', 'Brown Scramble Burrito'),
('buttered_biscuit', 'Buttered Biscuit'),
('chick_fil_a_nuggets', 'Chick-fil-A Nuggets'),
('chick_n_minis', 'Chick-n-Minis'),
('chick_n_strips', 'Chick-n-Strips'),
('chicken_noodle_soup', 'Chicken Noodle Soup'),
('chocolate_chunk_cookie', 'Chocolate Chunk Cookie'),
('chocolate_fudge_brownie', 'Chocolate Fudge Brownie'),
('cobb_salad', 'Cobb Salad'),
('cool_wrap', 'Cool Wrap'),
('english_muffin', 'English Muffin'),
('fruit_cup', 'Fruit Cup'),
('greek_yogurt_parfait', 'Greek Yogurt Parfait'),
('grilled_nuggets', 'Grilled Nuggets'),
('hash_browns', 'Hash Browns'),
('icedream_cone', 'Icedream Cone'),
('icedream_cup', 'Icedream Cup'),
('kale_crunch_side', 'Kale Crunch Side'),
('mac_cheese', 'Mac & Cheese'),
('market_salad', 'Market Salad'),
('side_salad', 'Side Salad'),
('spicy_southwest_salad', 'Spicy Southwest Salad'),
('waffle_potato_chips', 'Waffle Potato Chips'),
('waffle_potato_fries', 'Waffle Potato Fries'),
('chicken_biscuit', 'Chicken Biscuit'),
('egg_white_grill', 'Egg White Grill'),
('chicken_egg_cheese', 'Chicken, Egg & Cheese Biscuit'),
('sausage_egg_cheese', 'Sausage, Egg & Cheese Biscuit'),
('egg_cheese_muffin', 'Egg & Cheese Muffin'),
('chicken_sandwich', 'Chicken Sandwich'),
('deluxe_sandwich', 'Deluxe Sandwich'),
('chicken_club_sandwich', 'Chicken Club Sandwich'),
('apple_juice', 'Honest Kids Apple Juice'),
('apple_sauce', 'Apple Sauce'),
('brewed_iced_tea', 'Brewed Iced Tea'),
('chick_fil_a_lemonade', 'Chick-fil-A Lemonade'),
('chocolate_milk', 'Chocolate Milk'),
('chocolate_milkshake', 'Chocolate Milkshake'),
('coffee', 'Coffee'),
('cookies_cream_milkshake', 'Cookies & Cream Milkshake'),
('frosted_coffee', 'Frosted Coffee'),
('frosted_lemonade', 'Frosted Lemonade'),
('peach_milkshake', 'Peach Milkshake'),
('simply_orange', 'Simply Orange'),
('strawberry_milkshake', 'Strawberry Milkshake'),
('sweet_tea', 'Sweet Tea'),
('vanilla_milkshake', 'Vanilla Milkshake')
;