INSERT INTO `items` (`name`, `label`) VALUES
('big_mac', 'Big Mac'),
('chicken_mcnuggets', 'Chicken McNuggets'),
('crispy_chicken_sandwich', 'Crispy Chicken Sandwich'),
('double_quarter_pounder', 'Double Quarter Pounder'),
('egg_mcmuffin', 'Egg McMuffin'),
('quarter_pounder', 'Quarter Pounder'),
('quarter_pounder_cheese', 'Quarter Pounder Cheese'),
('sausage_biscuit', 'Sausage Biscuit'),
('sausage_burrito', 'Sausage Burrito'),
('spicy_crispy_chicken_sandwich', 'Spicy Crispy Chicken Sandwich'),
('spicy_deluxe_sandwich', 'Spicy Deluxe Sandwich'),
('big_mac_combo', 'Big Mac Combo'),
('cheeseburger_combo_meal', 'Cheeseburger Combo Meal'),
('deluxe_crispy_sandwich_combo', 'Deluxe Crispy Sandwich Combo'),
('double_quarter_combo', 'Double Quarter Combo'),
('egg_cheese_biscuit', 'Egg Cheese Biscuit'),
('mc_combo_chicken', 'Combo Chicken'),
('mc_nuggets_happy_meal', 'McNuggets Happy Meal'),
('spicy_chicken_sandwich_combo', 'Spicy Chicken Sandwich Combo'),
('world_famous_fries', 'World Famous Fries'),
('hot_fudge_sundae', 'Hot Fudge Sundae'),
('mc_cappuccino', 'Cappuccino'),
('mc_diet_coke', 'Diet Coke'),
('mc_dr_pepper', 'Dr Pepper'),
('mc_fanta_orange', 'Fanta Orange'),
('mc_flurry_candies', 'McFlurry Candies'),
('mc_flurry_cookies', 'McFlurry Cookies'),
('mc_fruit_punch', 'Fruit Punch'),
('mc_hot_chocolate', 'Hot Chocolate'),
('mc_iced_coffee', 'Iced Coffee'),
('mc_iced_tea', 'Iced Tea'),
('mc_sprite', 'Sprite'),
('mc_strawberry_shake', 'Strawberry Shake'),
('mc_vanilla_shake', 'Vanilla Shake'),
('orange_juice', 'Orange Juice'),
('strawberry_watermelon_slushie', 'Strawberry Watermelon Slushie'),
('tropical_mango_slushie', 'Tropical Mango Slushie')
;